# Generated by Django 5.2.4 on 2025-07-21 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialgraph', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='title',
        ),
    ]
