# Generated by Django 5.2.4 on 2025-07-23 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialgraph', '0003_add_unique_profile_linkedin_url_and_no_blank_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='website',
            field=models.URLField(blank=True, verbose_name='website'),
        ),
    ]
