# Generated by Django 5.0.2 on 2024-08-26 06:47

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dual_use', '0002_alter_company_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Grant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='name')),
                ('program_name', models.CharField(blank=True, max_length=255, verbose_name='program name')),
                ('phase', models.CharField(blank=True, max_length=255, verbose_name='phase')),
                ('branch', models.CharField(blank=True, max_length=255, verbose_name='branch')),
                ('award_url', models.URLField(blank=True, verbose_name='award URL')),
                ('award_year', models.PositiveIntegerField(blank=True, null=True, verbose_name='award year')),
                ('award_month', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='award month')),
                ('award_date', models.DateField(blank=True, null=True, verbose_name='award date')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('granting_agency', models.CharField(blank=True, max_length=255, verbose_name='granting agency')),
                ('obligated_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='obligated amount (USD)')),
                ('potential_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='potential amount (USD)')),
                ('extras', models.JSONField(blank=True, default=dict, verbose_name='extras')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='updated at')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grants', related_query_name='grant', to='dual_use.company', verbose_name='company')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_du_grants', related_query_name='created_ud_grant', to=settings.AUTH_USER_MODEL, verbose_name='creator')),
            ],
            options={
                'verbose_name': 'Grant',
                'verbose_name_plural': 'Grants',
                'indexes': [models.Index(fields=['award_year', 'award_month'], name='du_grant_award_year_month_idx')],
            },
        ),
    ]
