# Generated by Django 5.0.2 on 2024-08-26 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dual_use', '0003_grant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='founders_names',
        ),
    ]
