# Generated by Django 5.0.2 on 2024-08-26 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dual_use', '0004_remove_company_founders_names'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='cb_uuid',
            field=models.UUIDField(blank=True, null=True, unique=True, verbose_name='crunchbase UUID'),
        ),
    ]
