# Generated by Django 5.0.2 on 2024-08-26 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dual_use', '0005_company_cb_uuid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='industries_names_cb',
            new_name='cb_industries_names',
        ),
    ]
