# Generated by Django 5.0.2 on 2024-08-26 08:25

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dual_use', '0006_rename_industries_names_cb_company_cb_industries_names'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='cb_industries_names',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, size=None, verbose_name='crunchbase industries'),
        ),
    ]
