# Generated by Django 5.0.2 on 2024-08-26 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dual_use', '0007_alter_company_cb_industries_names'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(db_index=True, max_length=255, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='company',
            name='website',
            field=models.URLField(blank=True, db_index=True, verbose_name='website'),
        ),
        migrations.AlterField(
            model_name='company',
            name='year_evaluated',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True, verbose_name='year evaluated'),
        ),
        migrations.AlterField(
            model_name='company',
            name='year_founded',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True, verbose_name='year founded'),
        ),
    ]
