# Generated by Django 5.0.2 on 2024-08-26 09:09

import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dual_use', '0008_add_some_indexes_to_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='hq_country_name',
            field=django_countries.fields.CountryField(blank=True, max_length=2, verbose_name='HQ country'),
        ),
    ]
