# Generated by Django 5.0.2 on 2024-08-26 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dual_use', '0009_alter_company_hq_country_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='hq_state_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='HQ state/region'),
        ),
    ]
