# Generated by Django 5.0.2 on 2024-08-26 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dual_use', '0010_alter_company_hq_state_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='hq_country_name',
            new_name='hq_country',
        ),
    ]
