# Generated by Django 5.0.2 on 2024-08-26 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dual_use', '0011_rename_hq_country_name_company_hq_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundingstatus',
            name='code',
            field=models.CharField(blank=True, max_length=255, verbose_name='code'),
        ),
        migrations.AddField(
            model_name='fundingtype',
            name='code',
            field=models.CharField(blank=True, max_length=255, verbose_name='code'),
        ),
        migrations.AddField(
            model_name='industry',
            name='code',
            field=models.CharField(blank=True, max_length=255, verbose_name='code'),
        ),
        migrations.AddField(
            model_name='technologytype',
            name='code',
            field=models.CharField(blank=True, max_length=255, verbose_name='code'),
        ),
        migrations.AlterField(
            model_name='fundingstatus',
            name='name',
            field=models.CharField(max_length=255, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='fundingtype',
            name='name',
            field=models.CharField(max_length=255, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='industry',
            name='name',
            field=models.CharField(max_length=255, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='technologytype',
            name='name',
            field=models.CharField(max_length=255, verbose_name='name'),
        ),
    ]
