# Generated by Django 5.0.2 on 2024-08-26 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dual_use', '0012_add_code_to_some_fields'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FundingStatus',
            new_name='FundingStage',
        ),
        migrations.AlterModelOptions(
            name='fundingstage',
            options={'verbose_name': 'Funding Stage', 'verbose_name_plural': 'Funding Stages'},
        ),
    ]
