# Generated by Django 5.0.2 on 2024-08-26 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dual_use', '0013_rename_fundingstatus_fundingstage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='funding_status',
        ),
        migrations.AddField(
            model_name='company',
            name='funding_stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companies', related_query_name='company', to='dual_use.fundingstage', verbose_name='funding stage'),
        ),
    ]
