# Generated by Django 5.0.2 on 2024-08-26 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dual_use', '0014_remove_company_funding_status_company_funding_stage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundingstage',
            name='code',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='code'),
        ),
        migrations.AlterField(
            model_name='fundingstage',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='fundingtype',
            name='code',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='code'),
        ),
        migrations.AlterField(
            model_name='fundingtype',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='industry',
            name='code',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='code'),
        ),
        migrations.AlterField(
            model_name='industry',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='technologytype',
            name='code',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='code'),
        ),
        migrations.AlterField(
            model_name='technologytype',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='name'),
        ),
    ]
