# Generated by Django 5.0.2 on 2024-08-27 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dual_use', '0015_add_unique_constrain_on_code_and_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='cb_url',
            field=models.URLField(blank=True, verbose_name='crunchbase URL'),
        ),
    ]
