# Generated by Django 5.0.2 on 2024-08-27 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dual_use', '0017_company_extras'),
    ]

    operations = [
        migrations.AddField(
            model_name='founder',
            name='extras',
            field=models.JSONField(blank=True, default=dict, verbose_name='extras'),
        ),
    ]
