# Generated by Django 5.0.2 on 2024-08-29 06:27

import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dual_use', '0018_founder_extras'),
    ]

    operations = [
        migrations.AddField(
            model_name='founder',
            name='country',
            field=django_countries.fields.CountryField(blank=True, max_length=2, verbose_name='country'),
        ),
        migrations.AddField(
            model_name='founder',
            name='location',
            field=models.CharField(blank=True, max_length=255, verbose_name='location'),
        ),
    ]
