# Generated by Django 5.0.2 on 2024-08-29 10:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dual_use', '0019_founder_country_founder_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='FounderExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('company_name', models.CharField(blank=True, max_length=255, verbose_name='company name')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='title')),
                ('location', models.CharField(blank=True, max_length=255, verbose_name='location')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('website', models.URLField(blank=True, verbose_name='website')),
                ('linkedin_url', models.URLField(blank=True, verbose_name='linkedin URL')),
                ('date_from', models.CharField(blank=True, max_length=255, verbose_name='from date')),
                ('date_to', models.CharField(blank=True, max_length=255, verbose_name='to date')),
                ('duration', models.DurationField(blank=True, null=True, verbose_name='duration')),
                ('extras', models.JSONField(blank=True, default=dict, verbose_name='extras')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='updated at')),
                ('founder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='experiences', related_query_name='experience', to='dual_use.founder', verbose_name='founder')),
            ],
            options={
                'verbose_name': 'Founder Experience',
                'verbose_name_plural': 'Founders Experiences',
            },
        ),
    ]
