# Generated by Django 5.0.2 on 2024-08-29 11:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dual_use', '0020_founderexperience'),
    ]

    operations = [
        migrations.CreateModel(
            name='FounderEducation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('institution_name', models.CharField(blank=True, max_length=255, verbose_name='institution name')),
                ('program_name', models.CharField(blank=True, max_length=255, verbose_name='program')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('website', models.URLField(blank=True, verbose_name='institution website')),
                ('linkedin_url', models.URLField(blank=True, verbose_name='institution linkedin URL')),
                ('date_from', models.CharField(blank=True, max_length=255, verbose_name='from date')),
                ('date_to', models.CharField(blank=True, max_length=255, verbose_name='to date')),
                ('extras', models.JSONField(blank=True, default=dict, verbose_name='extras')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='updated at')),
                ('founder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='educations', related_query_name='education', to='dual_use.founder', verbose_name='founder')),
            ],
            options={
                'verbose_name': 'Founder Education',
                'verbose_name_plural': 'Founders Education',
            },
        ),
    ]
