# Generated by Django 5.0.2 on 2024-09-09 07:44

import dual_use.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dual_use', '0021_foundereducation'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=dual_use.files.storage.company_image_path, verbose_name='image'),
        ),
    ]
