# Generated by Django 5.0.2 on 2024-09-11 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dual_use', '0023_ipostatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='ipo_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companies', related_query_name='company', to='dual_use.ipostatus', verbose_name='IPO status'),
        ),
    ]
