# Generated by Django 5.0.2 on 2024-09-11 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dual_use', '0024_company_ipo_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='linkedin_url',
            field=models.URLField(blank=True, verbose_name='linkedin URL'),
        ),
    ]
