# Generated by Django 5.0.2 on 2024-09-12 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dual_use', '0025_company_linkedin_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='acquirer_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='acquired by'),
        ),
    ]
