# Generated by Django 5.0.2 on 2024-09-12 07:23

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dual_use', '0027_company_accelerators_names'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='investors_names',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, size=None, verbose_name='investors names'),
        ),
    ]
