# Generated by Django 5.0.2 on 2024-09-12 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dual_use', '0028_alter_company_investors_names'),
    ]

    operations = [
        migrations.AlterField(
            model_name='founder',
            name='prior_founding_count',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='number of prior founding attempts'),
        ),
    ]
