# Generated by Django 5.0.2 on 2024-09-18 08:02

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dual_use', '0029_alter_founder_prior_founding_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='founder',
            name='military_or_govt_background',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, help_text='example: government agency, army, air force, navy', size=None, verbose_name='government or military background'),
        ),
    ]
