# Generated by Django 5.0.2 on 2024-09-30 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dual_use', '0030_founder_military_or_govt_background'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='summary',
            field=models.TextField(blank=True, help_text='short description', verbose_name='summary'),
        ),
        migrations.AlterField(
            model_name='company',
            name='description',
            field=models.TextField(blank=True, help_text='full description', verbose_name='description'),
        ),
    ]
