# Generated by Django 5.0.2 on 2024-10-09 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dual_use', '0031_company_summary'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='has_african_on_founders',
            new_name='has_black_on_founders',
        ),
    ]
