# Generated by Django 5.0.2 on 2024-10-14 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dual_use', '0032_rename_has_african_on_founders_company_has_black_on_founders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='founder',
            name='age_at_founding',
            field=models.PositiveIntegerField(blank=True, help_text='Can be estimated based on assumption the founder graduated with 22 years old.', null=True, verbose_name='age at founding'),
        ),
        migrations.AlterField(
            model_name='founder',
            name='bachelor_grad_year',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name="bachelor's graduation year"),
        ),
    ]
