# Generated by Django 5.0.2 on 2024-10-21 17:29

from django.conf import settings
from django.db import migrations, models


def _set_cb_url_nulls(apps, schema_editor):
    company_model = apps.get_model('dual_use', 'Company')
    db_alias = schema_editor.connection.alias
    company_model.objects.using(db_alias)\
        .filter(cb_url='')\
        .update(cb_url=None)


def _set_cb_url_blanks(apps, schema_editor):
    company_model = apps.get_model('dual_use', 'Company')
    db_alias = schema_editor.connection.alias
    company_model.objects.using(db_alias)\
        .filter(cb_url=None)\
        .update(cb_url='')


class Migration(migrations.Migration):

    dependencies = [
        ('dual_use', '0033_alter_founder_fields_help_text'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='cb_url',
            field=models.URLField(blank=True, null=True, verbose_name='crunchbase URL'),
        ),
        migrations.RunPython(
            _set_cb_url_nulls,
            reverse_code=_set_cb_url_blanks
        ),
        migrations.AlterField(
            model_name='company',
            name='cb_uuid',
            field=models.UUIDField(blank=True, null=True, verbose_name='crunchbase UUID'),
        ),
        migrations.AddConstraint(
            model_name='company',
            constraint=models.UniqueConstraint(fields=('cb_uuid', 'year_evaluated'), name='dual_use_company_cb_uuid_year_evaluated_key'),
        ),
        migrations.AddConstraint(
            model_name='company',
            constraint=models.UniqueConstraint(fields=('cb_url', 'year_evaluated'), name='dual_use_company_cb_url_year_evaluated_key'),
        ),
    ]
