# Generated by Django 5.0.2 on 2024-11-05 22:27

import django.contrib.postgres.fields.ranges
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dual_use', '0035_add_cb_fields_to_company'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='apps_downloads_count_30d',
            new_name='apps_downloads_count_d30',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='trademark_patent_class',
            new_name='popular_trademark_class',
        ),
        migrations.RemoveField(
            model_name='company',
            name='acquirer_url',
        ),
        migrations.RemoveField(
            model_name='company',
            name='web_avg_visits_6m',
        ),
        migrations.AddField(
            model_name='company',
            name='acquired_on_precision',
            field=models.CharField(blank=True, help_text='precision of date the acquisition was announced', null=True, verbose_name='acquired on precision'),
        ),
        migrations.AddField(
            model_name='company',
            name='acquirer_cb_url',
            field=models.URLField(blank=True, verbose_name='acquirer crunchbase URL'),
        ),
        migrations.AddField(
            model_name='company',
            name='acquisition_cb_url',
            field=models.URLField(blank=True, verbose_name='acquisition crunchbase URL'),
        ),
        migrations.AddField(
            model_name='company',
            name='closed_on_precision',
            field=models.CharField(blank=True, max_length=64, verbose_name='precision of closing date'),
        ),
        migrations.AddField(
            model_name='company',
            name='delisted_on_precision',
            field=models.CharField(blank=True, max_length=64, verbose_name='delisted date precision'),
        ),
        migrations.AddField(
            model_name='company',
            name='exit_on_precision',
            field=models.CharField(blank=True, max_length=64, verbose_name='precision of exit date'),
        ),
        migrations.AddField(
            model_name='company',
            name='founded_on',
            field=models.DateField(blank=True, null=True, verbose_name='date founded'),
        ),
        migrations.AddField(
            model_name='company',
            name='founded_on_precision',
            field=models.CharField(blank=True, max_length=64, verbose_name='precision of date founded'),
        ),
        migrations.AddField(
            model_name='company',
            name='stock_cb_url',
            field=models.URLField(blank=True, verbose_name='stock crunchbase URL'),
        ),
        migrations.AddField(
            model_name='company',
            name='web_avg_visits_m6',
            field=models.PositiveBigIntegerField(blank=True, null=True, verbose_name='web average monthly visits (6 months)'),
        ),
        migrations.AlterField(
            model_name='company',
            name='num_employees_range',
            field=django.contrib.postgres.fields.ranges.IntegerRangeField(blank=True, null=True, verbose_name='number of employees (range)'),
        ),
        migrations.AlterField(
            model_name='company',
            name='web_monthly_visits',
            field=models.PositiveBigIntegerField(blank=True, null=True, verbose_name='web monthly visits'),
        ),
    ]
