# Generated by Django 5.0.2 on 2024-11-13 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dual_use', '0036_add_cb_fields_to_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='is_reviewed',
            field=models.BooleanField(blank=True, default=False, verbose_name='is reviewed'),
        ),
    ]
