# Generated by Django 5.0.2 on 2024-12-04 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dual_use', '0037_company_is_reviewed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grant',
            name='award_url',
        ),
        migrations.AddField(
            model_name='company',
            name='duns',
            field=models.IntegerField(blank=True, null=True, verbose_name='D-U-N-S number'),
        ),
        migrations.AddField(
            model_name='company',
            name='hq_address_line_1',
            field=models.CharField(blank=True, max_length=255, verbose_name='address line 1'),
        ),
        migrations.AddField(
            model_name='company',
            name='hq_address_line_2',
            field=models.CharField(blank=True, max_length=255, verbose_name='address line 2'),
        ),
        migrations.AddField(
            model_name='company',
            name='nid',
            field=models.IntegerField(blank=True, null=True, verbose_name='Company NID'),
        ),
        migrations.AddField(
            model_name='grant',
            name='sbir_id',
            field=models.CharField(blank=True, max_length=255, verbose_name='SBIR award ID'),
        ),
    ]
