# Generated by Django 5.0.2 on 2025-01-10 12:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dual_use', '0038_add_award_duns_nid_and_address_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Company',
            new_name='Report',
        ),
        migrations.RemoveConstraint(
            model_name='report',
            name='dual_use_company_cb_uuid_year_evaluated_key',
        ),
        migrations.RemoveConstraint(
            model_name='report',
            name='dual_use_company_cb_url_year_evaluated_key',
        ),
        migrations.AddConstraint(
            model_name='report',
            constraint=models.UniqueConstraint(fields=('cb_uuid', 'year_evaluated'), name='dual_use_report_cb_uuid_year_evaluated_key'),
        ),
        migrations.AddConstraint(
            model_name='report',
            constraint=models.UniqueConstraint(fields=('cb_url', 'year_evaluated'), name='dual_use_report_cb_url_year_evaluated_key'),
        ),
    ]
