# Generated by Django 5.0.2 on 2025-01-10 13:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dual_use', '0039_rename_company_report_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='report',
            options={'verbose_name': 'Report', 'verbose_name_plural': 'Reports'},
        ),
        migrations.RenameField(
            model_name='founder',
            old_name='company',
            new_name='report',
        ),
        migrations.RenameField(
            model_name='grant',
            old_name='company',
            new_name='report',
        ),
        migrations.AlterField(
            model_name='report',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_du_reports', related_query_name='created_du_report', to=settings.AUTH_USER_MODEL, verbose_name='creator'),
        ),
        migrations.AlterField(
            model_name='report',
            name='funding_stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', related_query_name='report', to='dual_use.fundingstage', verbose_name='funding stage'),
        ),
        migrations.AlterField(
            model_name='report',
            name='ipo_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', related_query_name='report', to='dual_use.ipostatus', verbose_name='IPO status'),
        ),
        migrations.AlterField(
            model_name='report',
            name='last_equity_funding_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_equity_last', related_query_name='report_equity_last', to='dual_use.fundingtype', verbose_name='last equity funding type'),
        ),
        migrations.AlterField(
            model_name='report',
            name='last_funding_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_last', related_query_name='report_last', to='dual_use.fundingtype', verbose_name='last funding round type'),
        ),
        migrations.AlterField(
            model_name='report',
            name='technology_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', related_query_name='report', to='dual_use.technologytype', verbose_name='technology type'),
        ),
    ]
