# Generated by Django 5.0.2 on 2025-01-10 13:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dual_use', '0040_rename_company_relations_to_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='founder',
            name='report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='founders', related_query_name='founder', to='dual_use.report', verbose_name='report'),
        ),
        migrations.AlterField(
            model_name='grant',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grants', related_query_name='grant', to='dual_use.report', verbose_name='report'),
        ),
        migrations.AlterField(
            model_name='report',
            name='industries',
            field=models.ManyToManyField(blank=True, related_name='reports', related_query_name='report', to='dual_use.industry', verbose_name='industries'),
        ),
        migrations.AlterField(
            model_name='report',
            name='investment_stages',
            field=models.ManyToManyField(blank=True, help_text='the stages of investments made by this organization', related_name='investors_reports', related_query_name='investor_report', to='dual_use.fundingstage', verbose_name='investment stages'),
        ),
        migrations.AlterField(
            model_name='report',
            name='investor_types',
            field=models.ManyToManyField(blank=True, help_text='type of investor this organization is (e.g. Angel, Fund of Funds, Venture Capital)', related_name='reports', related_query_name='report', to='dual_use.investortype', verbose_name='investor type'),
        ),
    ]
