# Generated by Django 5.0.2 on 2025-01-15 06:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        ('dual_use', '0041_rename_company_relations_to_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='du_reports', related_query_name='du_report', to='companies.company', verbose_name='company'),
        ),
    ]
