# Generated by Django 5.0.2 on 2025-01-17 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dual_use', '0042_report_company'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='founding_rounds_count',
            new_name='funding_rounds_count',
        ),
        migrations.AlterField(
            model_name='report',
            name='funding_rounds_count',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='number of funding rounds'),
        ),
    ]
