# Generated by Django 5.0.2 on 2025-01-25 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0021_company_hq_regions_names'),
        ('dual_use', '0043_rename_founding_rounds_count_report_funding_rounds_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='funding_stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='du_reports', related_query_name='du_report', to='companies.fundingstage', verbose_name='funding stage'),
        ),
        migrations.AlterField(
            model_name='report',
            name='industries',
            field=models.ManyToManyField(blank=True, related_name='du_reports', related_query_name='du_report', to='companies.industry', verbose_name='industries'),
        ),
        migrations.AlterField(
            model_name='report',
            name='investment_stages',
            field=models.ManyToManyField(blank=True, help_text='the stages of investments made by this organization', related_name='du_investors_reports', related_query_name='du_investor_report', to='companies.fundingstage', verbose_name='investment stages'),
        ),
        migrations.AlterField(
            model_name='report',
            name='investor_types',
            field=models.ManyToManyField(blank=True, help_text='type of investor this organization is (e.g. Angel, Fund of Funds, Venture Capital)', related_name='du_reports', related_query_name='du_report', to='companies.investortype', verbose_name='investor type'),
        ),
        migrations.AlterField(
            model_name='report',
            name='ipo_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='du_reports', related_query_name='du_report', to='companies.ipostatus', verbose_name='IPO status'),
        ),
        migrations.AlterField(
            model_name='report',
            name='last_equity_funding_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='du_reports_equity_last', related_query_name='du_report_equity_last', to='companies.fundingtype', verbose_name='last equity funding type'),
        ),
        migrations.AlterField(
            model_name='report',
            name='last_funding_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='du_reports_last', related_query_name='du_report_last', to='companies.fundingtype', verbose_name='last funding round type'),
        ),
        migrations.AlterField(
            model_name='report',
            name='technology_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='du_reports', related_query_name='du_report', to='companies.technologytype', verbose_name='technology type'),
        ),
    ]
