# Generated by Django 5.0.2 on 2025-01-25 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dual_use', '0044_migrate_report_relations_to_companies_models'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FundingStage',
        ),
        migrations.DeleteModel(
            name='FundingType',
        ),
        migrations.DeleteModel(
            name='Industry',
        ),
        migrations.DeleteModel(
            name='InvestorType',
        ),
        migrations.DeleteModel(
            name='IPOStatus',
        ),
        migrations.DeleteModel(
            name='TechnologyType',
        ),
    ]
