# Generated by Django 5.1.8 on 2025-06-02 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dual_use", "0045_delete_du_models_migrated_to_companies"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="founder",
            name="creator",
        ),
        migrations.RemoveField(
            model_name="founder",
            name="report",
        ),
        migrations.RemoveField(
            model_name="founderexperience",
            name="founder",
        ),
        migrations.RemoveField(
            model_name="grant",
            name="creator",
        ),
        migrations.RemoveField(
            model_name="grant",
            name="report",
        ),
        migrations.DeleteModel(
            name="FounderEducation",
        ),
        migrations.DeleteModel(
            name="Founder",
        ),
        migrations.DeleteModel(
            name="FounderExperience",
        ),
        migrations.DeleteModel(
            name="Grant",
        ),
    ]
