#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

python manage.py migrate
python manage.py collectstatic --no-input --clear

exec gunicorn brain.wsgi --bind 0.0.0.0:5000 --chdir=/brain --timeout 300
