# Generated by Django 5.2.4 on 2025-07-08 13:18

import django.db.models.deletion
import django.db.models.functions.datetime
import django_countries.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                (
                    'country',
                    django_countries.fields.CountryField(
                        blank=True,
                        db_index=True,
                        help_text='The country to which the state belongs.',
                        max_length=2,
                        verbose_name='country',
                    ),
                ),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                (
                    'code',
                    models.SlugField(blank=True, help_text='A unique short code for the state.', verbose_name='code'),
                ),
                (
                    'description',
                    models.TextField(
                        blank=True, help_text='A long-form description of the state.', verbose_name='description'
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(
                        auto_now_add=True,
                        db_default=django.db.models.functions.datetime.Now(),
                        help_text='The database level timestamp of when the record was created.',
                        verbose_name='created at',
                    ),
                ),
                (
                    'updated_at',
                    models.DateTimeField(
                        auto_now=True,
                        help_text='The database level timestamp of when the record was last modified.',
                        null=True,
                        verbose_name='updated at',
                    ),
                ),
            ],
            options={
                'verbose_name': 'State',
                'verbose_name_plural': 'States',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                (
                    'country',
                    django_countries.fields.CountryField(
                        blank=True,
                        db_index=True,
                        help_text='The country to which the city belongs.',
                        max_length=2,
                        verbose_name='country',
                    ),
                ),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                (
                    'code',
                    models.SlugField(blank=True, help_text='A unique short code for the city.', verbose_name='code'),
                ),
                (
                    'description',
                    models.TextField(
                        blank=True, help_text='A long-form description of the city.', verbose_name='description'
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(
                        auto_now_add=True,
                        db_default=django.db.models.functions.datetime.Now(),
                        help_text='The database level timestamp of when the record was created.',
                        verbose_name='created at',
                    ),
                ),
                (
                    'updated_at',
                    models.DateTimeField(
                        auto_now=True,
                        help_text='The database level timestamp of when the record was last modified.',
                        null=True,
                        verbose_name='updated at',
                    ),
                ),
                (
                    'state',
                    models.ForeignKey(
                        blank=True,
                        help_text='The state/region to which the city belongs.',
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='cities',
                        related_query_name='city',
                        to='locations.state',
                        verbose_name='state',
                    ),
                ),
            ],
            options={
                'verbose_name': 'City',
                'verbose_name_plural': 'Cities',
            },
        ),
    ]
