# Generated by Django 5.2.4 on 2025-07-18 20:27

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0004_dealassessment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dealassessment',
            options={'verbose_name': 'Deal Assessment', 'verbose_name_plural': 'Deal Assessments'},
        ),
        migrations.RemoveField(
            model_name='dealassessment',
            name='confidence',
        ),
        migrations.AddField(
            model_name='dealassessment',
            name='auto_thesis_fit_score',
            field=models.FloatField(blank=True, null=True, verbose_name='thesis fit score'),
        ),
        migrations.AddField(
            model_name='dealassessment',
            name='feasibility',
            field=models.TextField(
                blank=True, help_text='How feasible is the company’s planned product?', verbose_name='feasibility'
            ),
        ),
        migrations.AddField(
            model_name='dealassessment',
            name='parent_breakthroughs',
            field=models.TextField(
                blank=True,
                help_text='What recent breakthroughs have made this technology newly possible?',
                verbose_name='SOTA parent breakthroughs',
            ),
        ),
        migrations.AddField(
            model_name='dealassessment',
            name='sota_comparison',
            field=models.TextField(
                blank=True,
                help_text="How does this company's technology compare to the state of the art?",
                verbose_name='SOTA comparison',
            ),
        ),
        migrations.AddField(
            model_name='dealassessment',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=255), blank=True, default=list, size=None, verbose_name='tags'
            ),
        ),
        migrations.AddField(
            model_name='dealassessment',
            name='technical_risk',
            field=models.TextField(
                blank=True, help_text=' What are the major areas of technical risk?', verbose_name='technical risk'
            ),
        ),
    ]
