# Generated by Django 5.2.4 on 2025-07-18 21:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_company_affinity_id'),
        ('deals', '0006_remove_duplicated_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deal',
            name='stage',
        ),
        migrations.AddField(
            model_name='deal',
            name='funding_stage',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='deals',
                related_query_name='deal',
                to='companies.fundingstage',
                verbose_name='funding stage',
            ),
        ),
        migrations.AddField(
            model_name='deal',
            name='funding_type',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='deals',
                related_query_name='deal',
                to='companies.fundingtype',
                verbose_name='funding type',
            ),
        ),
        migrations.AddField(
            model_name='dealassessment',
            name='confidence',
            field=models.CharField(
                blank=True,
                choices=[('high', 'High'), ('low', 'Low')],
                help_text='Based on data completeness',
                max_length=50,
                verbose_name='confidence',
            ),
        ),
        migrations.AlterField(
            model_name='dealassessment',
            name='technical_risk',
            field=models.TextField(
                blank=True, help_text='What are the major areas of technical risk?', verbose_name='technical risk'
            ),
        ),
    ]
