# Generated by Django 5.2.4 on 2025-07-18 21:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_company_affinity_id'),
        ('deals', '0007_cleanup_and_add_funding_status_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='company',
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='deals',
                related_query_name='deal',
                to='companies.company',
                verbose_name='company',
            ),
        ),
    ]
