# Generated by Django 5.2.4 on 2025-07-18 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0008_make_deal_company_non_nullable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deck',
            name='file_format',
            field=models.CharField(
                blank=True, choices=[('pdf', 'PDF')], default='pdf', max_length=255, verbose_name='file format'
            ),
        ),
    ]
