# Generated by Django 5.2.4 on 2025-07-21 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0009_alter_deck_file_format_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='dualusecategory',
            name='code',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='code'),
        ),
        migrations.AddField(
            model_name='dualusesignal',
            name='code',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='code'),
        ),
    ]
