# Generated by Django 5.2.4 on 2025-07-21 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0006_rename_past_significant_employment_founding_past_significant_employments'),
        ('deals', '0010_add_dualusecategory_code_dualusesignal_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='misseddeal',
            name='company',
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='missed_deals',
                related_query_name='missed_deal',
                to='companies.company',
                verbose_name='company',
            ),
        ),
    ]
