# Generated by Django 5.2.4 on 2025-07-21 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0011_alter_misseddeal_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deck',
            name='file_format',
        ),
    ]
