# Generated by Django 5.2.4 on 2025-07-21 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0012_remove_deck_file_format'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deck',
            name='ingestion_status',
        ),
        migrations.RemoveField(
            model_name='deck',
            name='ingestion_task_id',
        ),
        migrations.AddField(
            model_name='dealfile',
            name='processing_status',
            field=models.CharField(
                blank=True,
                choices=[
                    ('PENDING', 'Pending'),
                    ('STARTED', 'Started processing'),
                    ('SUCCESS', 'Successful'),
                    ('FAILURE', 'Failed'),
                    ('RETRY', 'Retrying'),
                    ('REVOKED', 'Revoked'),
                ],
                max_length=255,
                verbose_name='processing status',
            ),
        ),
        migrations.AddField(
            model_name='dealfile',
            name='processing_task_id',
            field=models.CharField(blank=True, max_length=255, verbose_name='processing task ID'),
        ),
    ]
