# Generated by Django 5.2.4 on 2025-07-21 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0013_add_dealfile_processing_status_and_task_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealassessment',
            name='deal',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='assessments',
                related_query_name='assessment',
                to='deals.deal',
                verbose_name='deal',
            ),
        ),
    ]
