# Generated by Django 5.2.4 on 2025-07-21 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0014_alter_dealassessment_deal'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dealfile',
            options={'verbose_name': 'Deal File', 'verbose_name_plural': 'Deal Files'},
        ),
        migrations.AddField(
            model_name='dealfile',
            name='description',
            field=models.TextField(blank=True, verbose_name='description'),
        ),
    ]
