# Generated by Django 5.2.4 on 2025-07-22 11:15

import django.db.models.deletion
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0015_add_dealfile_description'),
        ('library', '0003_add_paper_raw_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paper',
            fields=[
                (
                    'dealfile_ptr',
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to='deals.dealfile',
                    ),
                ),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('abstract', models.TextField(blank=True, verbose_name='abstract')),
                ('raw_text', models.TextField(blank=True, verbose_name='raw text')),
                ('text', models.TextField(blank=True, help_text='clean text', verbose_name='text')),
                (
                    'tldr',
                    models.TextField(
                        blank=True,
                        help_text='short summary of the paper, usually auto-generated.',
                        verbose_name='tl;dr',
                    ),
                ),
                (
                    'semantic_scholar_id',
                    models.SlugField(blank=True, null=True, unique=True, verbose_name='semantic scholar ID'),
                ),
                (
                    'arxiv_id',
                    models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='arXiv ID'),
                ),
                (
                    'publication_year',
                    models.PositiveIntegerField(blank=True, null=True, verbose_name='year published'),
                ),
                ('publication_date', models.DateField(blank=True, null=True, verbose_name='date published')),
                ('license', models.CharField(blank=True, max_length=255, verbose_name='license')),
                (
                    'embedding',
                    pgvector.django.vector.VectorField(
                        blank=True, dimensions=768, null=True, verbose_name='embedding'
                    ),
                ),
                (
                    'authors',
                    models.ManyToManyField(
                        blank=True,
                        related_name='deals_papers',
                        related_query_name='deal_paper',
                        to='library.paperauthor',
                        verbose_name='authors',
                    ),
                ),
                (
                    'document_types',
                    models.ManyToManyField(
                        blank=True,
                        related_name='deals_papers',
                        related_query_name='deal_paper',
                        to='library.documenttype',
                        verbose_name='document type',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Paper',
                'verbose_name_plural': 'Papers',
            },
            bases=('deals.dealfile',),
        ),
    ]
