# Generated by Django 5.2.4 on 2025-07-22 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0016_add_paper'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealfile',
            name='deal',
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='files',
                related_query_name='file',
                to='deals.deal',
                verbose_name='deal',
            ),
        ),
    ]
