# Generated by Django 5.2.4 on 2025-07-22 14:41

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0017_alter_dealfile_deal_make_non_nullable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deal',
            name='business_model',
        ),
        migrations.RemoveField(
            model_name='deal',
            name='competition',
        ),
        migrations.RemoveField(
            model_name='deal',
            name='cons',
        ),
        migrations.RemoveField(
            model_name='deal',
            name='intellectual_property',
        ),
        migrations.RemoveField(
            model_name='deal',
            name='investment_rationale',
        ),
        migrations.RemoveField(
            model_name='deal',
            name='market_sizing',
        ),
        migrations.RemoveField(
            model_name='deal',
            name='problem',
        ),
        migrations.RemoveField(
            model_name='deal',
            name='pros',
        ),
        migrations.RemoveField(
            model_name='deal',
            name='quality_percentile',
        ),
        migrations.RemoveField(
            model_name='deal',
            name='recommendation',
        ),
        migrations.RemoveField(
            model_name='deal',
            name='solution',
        ),
        migrations.RemoveField(
            model_name='deal',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='deal',
            name='thesis_fit',
        ),
        migrations.RemoveField(
            model_name='deal',
            name='traction',
        ),
        migrations.AddField(
            model_name='dealassessment',
            name='auto_auto_thesis_fit_score',
            field=models.FloatField(blank=True, editable=False, null=True, verbose_name='thesis fit score'),
        ),
        migrations.AddField(
            model_name='dealassessment',
            name='auto_business_model',
            field=models.TextField(blank=True, editable=False, verbose_name='business model'),
        ),
        migrations.AddField(
            model_name='dealassessment',
            name='auto_competition',
            field=models.TextField(blank=True, editable=False, verbose_name='competition'),
        ),
        migrations.AddField(
            model_name='dealassessment',
            name='auto_confidence',
            field=models.CharField(
                blank=True,
                choices=[('high', 'High'), ('low', 'Low')],
                editable=False,
                help_text='Based on data completeness',
                max_length=50,
                verbose_name='confidence',
            ),
        ),
        migrations.AddField(
            model_name='dealassessment',
            name='auto_cons',
            field=models.TextField(blank=True, editable=False, verbose_name='cons'),
        ),
        migrations.AddField(
            model_name='dealassessment',
            name='auto_feasibility',
            field=models.TextField(
                blank=True,
                editable=False,
                help_text='How feasible is the company’s planned product?',
                verbose_name='feasibility',
            ),
        ),
        migrations.AddField(
            model_name='dealassessment',
            name='auto_intellectual_property',
            field=models.TextField(blank=True, editable=False, verbose_name='intellectual property'),
        ),
        migrations.AddField(
            model_name='dealassessment',
            name='auto_investment_rationale',
            field=models.TextField(blank=True, editable=False, verbose_name='investment rationale'),
        ),
        migrations.AddField(
            model_name='dealassessment',
            name='auto_market_sizing',
            field=models.TextField(blank=True, editable=False, verbose_name='market sizing'),
        ),
        migrations.AddField(
            model_name='dealassessment',
            name='auto_non_numeric_score',
            field=models.CharField(
                blank=True,
                choices=[
                    ('excellent', 'Excellent'),
                    ('good', 'Good'),
                    ('average', 'Average'),
                    ('below average', 'Below average'),
                ],
                editable=False,
                max_length=50,
                verbose_name='non numeric score',
            ),
        ),
        migrations.AddField(
            model_name='dealassessment',
            name='auto_numeric_score',
            field=models.FloatField(blank=True, editable=False, null=True, verbose_name='numeric score'),
        ),
        migrations.AddField(
            model_name='dealassessment',
            name='auto_parent_breakthroughs',
            field=models.TextField(
                blank=True,
                editable=False,
                help_text='What recent breakthroughs have made this technology newly possible?',
                verbose_name='SOTA parent breakthroughs',
            ),
        ),
        migrations.AddField(
            model_name='dealassessment',
            name='auto_problem',
            field=models.TextField(blank=True, editable=False, verbose_name='problem'),
        ),
        migrations.AddField(
            model_name='dealassessment',
            name='auto_pros',
            field=models.TextField(blank=True, editable=False, verbose_name='pros'),
        ),
        migrations.AddField(
            model_name='dealassessment',
            name='auto_quality_percentile',
            field=models.CharField(
                blank=True,
                choices=[
                    ('top 1%', 'most interesting'),
                    ('top 5%', 'very interesting'),
                    ('top 10%', 'interesting'),
                    ('top 20%', 'potentially interesting'),
                    ('top 50%', 'not interesting'),
                ],
                editable=False,
                max_length=50,
                verbose_name='quality percentile',
            ),
        ),
        migrations.AddField(
            model_name='dealassessment',
            name='auto_recommendation',
            field=models.CharField(
                blank=True,
                choices=[('prep to call', 'prep to call'), ('prep to pass', 'prep to pass')],
                editable=False,
                max_length=50,
                verbose_name='recommendation',
            ),
        ),
        migrations.AddField(
            model_name='dealassessment',
            name='auto_solution',
            field=models.TextField(blank=True, editable=False, verbose_name='product/solution'),
        ),
        migrations.AddField(
            model_name='dealassessment',
            name='auto_sota_comparison',
            field=models.TextField(
                blank=True,
                editable=False,
                help_text="How does this company's technology compare to the state of the art?",
                verbose_name='SOTA comparison',
            ),
        ),
        migrations.AddField(
            model_name='dealassessment',
            name='auto_tags',
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=255),
                blank=True,
                default=list,
                editable=False,
                size=None,
                verbose_name='tags',
            ),
        ),
        migrations.AddField(
            model_name='dealassessment',
            name='auto_technical_risk',
            field=models.TextField(
                blank=True,
                editable=False,
                help_text='What are the major areas of technical risk?',
                verbose_name='technical risk',
            ),
        ),
        migrations.AddField(
            model_name='dealassessment',
            name='auto_thesis_fit',
            field=models.TextField(blank=True, editable=False, verbose_name='thesis fit'),
        ),
        migrations.AddField(
            model_name='dealassessment',
            name='auto_traction',
            field=models.TextField(blank=True, editable=False, verbose_name='traction'),
        ),
    ]
