# Generated by Django 5.2.4 on 2025-07-26 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0018_restructure_deal_assessment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paper',
            options={'verbose_name': 'Deal Paper', 'verbose_name_plural': 'Deals Papers'},
        ),
    ]
