# Generated by Django 5.2.4 on 2025-07-30 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0019_alter_paper_meta_verbose_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dealfile',
            name='processing_status',
        ),
    ]
