# Generated by Django 5.2.4 on 2025-08-05 15:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0008_add_founding_update_and_created_at'),
        ('deals', '0020_remove_dealfile_processing_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='is_draft',
            field=models.BooleanField(blank=True, default=False, verbose_name='is draft'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='company',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='deals',
                related_query_name='deal',
                to='companies.company',
                verbose_name='company',
            ),
        ),
        migrations.AddConstraint(
            model_name='deal',
            constraint=models.CheckConstraint(
                condition=models.Q(models.Q(('company', None), _negated=True), ('is_draft', True), _connector='OR'),
                name='deals_deal_company_required_or_draft',
                violation_error_code='company_required',
                violation_error_message='Company is required if the deal is not a draft.',
            ),
        ),
    ]
