# Generated by Django 5.2.4 on 2025-08-05 16:21

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0021_add_deal_is_draft'),
    ]

    operations = [
        migrations.CreateModel(
            name='DraftDeal',
            fields=[],
            options={
                'verbose_name': 'Draft Deal',
                'verbose_name_plural': 'Draft Deals',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('deals.deal',),
        ),
        migrations.AlterModelOptions(
            name='deal',
            options={'default_manager_name': 'all_objects', 'verbose_name': 'Deal', 'verbose_name_plural': 'Deals'},
        ),
        migrations.AlterModelManagers(
            name='deal',
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
