# Generated by Django 5.2.4 on 2025-08-08 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0022_add_draftdeal_proxy'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='has_civilian_use',
            field=models.BooleanField(blank=True, null=True, verbose_name='has civilian use'),
        ),
    ]
