# Generated by Django 5.2.4 on 2025-08-08 10:32

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0023_add_deal_has_civilian_use'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='govt_relationships',
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=255),
                blank=True,
                default=list,
                size=None,
                verbose_name='government relationships',
            ),
        ),
    ]
