# Generated by Django 5.2.4 on 2025-08-08 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0024_add_deal_govt_relationships'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='status',
            field=models.CharField(
                blank=True,
                choices=[('new', 'new'), ('active', 'active'), ('subcommittee vetting', 'subcommittee vetting')],
                default='new',
                max_length=64,
                verbose_name='status',
            ),
        ),
    ]
