# Generated by Django 5.2.4 on 2025-08-11 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0025_add_deal_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealassessment',
            name='auto_auto_thesis_fit_score',
            field=models.FloatField(
                blank=True, editable=False, null=True, verbose_name='thesis fit score (automated)'
            ),
        ),
        migrations.AlterField(
            model_name='dealassessment',
            name='auto_business_model',
            field=models.TextField(blank=True, editable=False, verbose_name='business model (automated)'),
        ),
        migrations.AlterField(
            model_name='dealassessment',
            name='auto_competition',
            field=models.TextField(blank=True, editable=False, verbose_name='competition (automated)'),
        ),
        migrations.AlterField(
            model_name='dealassessment',
            name='auto_confidence',
            field=models.CharField(
                blank=True,
                choices=[('high', 'High'), ('low', 'Low')],
                editable=False,
                help_text='Based on data completeness',
                max_length=50,
                verbose_name='confidence (automated)',
            ),
        ),
        migrations.AlterField(
            model_name='dealassessment',
            name='auto_cons',
            field=models.TextField(blank=True, editable=False, verbose_name='cons (automated)'),
        ),
        migrations.AlterField(
            model_name='dealassessment',
            name='auto_intellectual_property',
            field=models.TextField(blank=True, editable=False, verbose_name='intellectual property ()'),
        ),
        migrations.AlterField(
            model_name='dealassessment',
            name='auto_investment_rationale',
            field=models.TextField(blank=True, editable=False, verbose_name='investment rationale (automated)'),
        ),
        migrations.AlterField(
            model_name='dealassessment',
            name='auto_market_sizing',
            field=models.TextField(blank=True, editable=False, verbose_name='total addressable market (automated)'),
        ),
        migrations.AlterField(
            model_name='dealassessment',
            name='auto_non_numeric_score',
            field=models.CharField(
                blank=True,
                choices=[
                    ('excellent', 'Excellent'),
                    ('good', 'Good'),
                    ('average', 'Average'),
                    ('below average', 'Below average'),
                ],
                editable=False,
                max_length=50,
                verbose_name='non numeric score (automated)',
            ),
        ),
        migrations.AlterField(
            model_name='dealassessment',
            name='auto_numeric_score',
            field=models.FloatField(blank=True, editable=False, null=True, verbose_name='numeric score (automated)'),
        ),
        migrations.AlterField(
            model_name='dealassessment',
            name='auto_problem',
            field=models.TextField(blank=True, editable=False, verbose_name='problem solved (automated)'),
        ),
        migrations.AlterField(
            model_name='dealassessment',
            name='auto_pros',
            field=models.TextField(blank=True, editable=False, verbose_name='pros (automated)'),
        ),
        migrations.AlterField(
            model_name='dealassessment',
            name='auto_quality_percentile',
            field=models.CharField(
                blank=True,
                choices=[
                    ('top 1%', 'most interesting'),
                    ('top 5%', 'very interesting'),
                    ('top 10%', 'interesting'),
                    ('top 20%', 'potentially interesting'),
                    ('top 50%', 'not interesting'),
                ],
                editable=False,
                max_length=50,
                verbose_name='quality percentile (automated)',
            ),
        ),
        migrations.AlterField(
            model_name='dealassessment',
            name='auto_recommendation',
            field=models.CharField(
                blank=True,
                choices=[('prep to call', 'prep to call'), ('prep to pass', 'prep to pass')],
                editable=False,
                max_length=50,
                verbose_name='recommendation (automated)',
            ),
        ),
        migrations.AlterField(
            model_name='dealassessment',
            name='auto_solution',
            field=models.TextField(blank=True, editable=False, verbose_name='product/solution (automated)'),
        ),
        migrations.AlterField(
            model_name='dealassessment',
            name='auto_thesis_fit',
            field=models.TextField(blank=True, editable=False, verbose_name='thesis fit evaluation (automated)'),
        ),
        migrations.AlterField(
            model_name='dealassessment',
            name='market_sizing',
            field=models.TextField(blank=True, verbose_name='total addressable market'),
        ),
        migrations.AlterField(
            model_name='dealassessment',
            name='problem',
            field=models.TextField(blank=True, verbose_name='problem solved'),
        ),
        migrations.AlterField(
            model_name='dealassessment',
            name='thesis_fit',
            field=models.TextField(blank=True, verbose_name='thesis fit evaluation'),
        ),
        migrations.AlterField(
            model_name='dealassessment',
            name='traction',
            field=models.TextField(blank=True, verbose_name='customer traction'),
        ),
    ]
