# Generated by Django 5.2.4 on 2025-08-11 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0026_dealassessment_update_labels'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dealassessment',
            old_name='auto_traction',
            new_name='auto_customer_traction',
        ),
        migrations.RenameField(
            model_name='dealassessment',
            old_name='auto_problem',
            new_name='auto_problem_solved',
        ),
        migrations.RenameField(
            model_name='dealassessment',
            old_name='auto_market_sizing',
            new_name='auto_tam',
        ),
        migrations.RenameField(
            model_name='dealassessment',
            old_name='auto_thesis_fit',
            new_name='auto_thesis_fit_evaluation',
        ),
        migrations.RenameField(
            model_name='dealassessment',
            old_name='traction',
            new_name='customer_traction',
        ),
        migrations.RenameField(
            model_name='dealassessment',
            old_name='problem',
            new_name='problem_solved',
        ),
        migrations.RenameField(
            model_name='dealassessment',
            old_name='market_sizing',
            new_name='tam',
        ),
        migrations.RenameField(
            model_name='dealassessment',
            old_name='thesis_fit',
            new_name='thesis_fit_evaluation',
        ),
        migrations.RemoveField(
            model_name='dealassessment',
            name='auto_auto_thesis_fit_score',
        ),
        migrations.AddField(
            model_name='dealassessment',
            name='thesis_fit_score',
            field=models.FloatField(blank=True, null=True, verbose_name='thesis fit score'),
        ),
        migrations.AlterField(
            model_name='dealassessment',
            name='auto_intellectual_property',
            field=models.TextField(blank=True, editable=False, verbose_name='intellectual property (automated)'),
        ),
        migrations.AlterField(
            model_name='dealassessment',
            name='auto_thesis_fit_score',
            field=models.FloatField(
                blank=True, editable=False, null=True, verbose_name='thesis fit score (automated)'
            ),
        ),
    ]
