# Generated by Django 5.2.4 on 2025-08-11 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0027_dealassessment_rename_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dealassessment',
            name='auto_feasibility',
        ),
        migrations.RemoveField(
            model_name='dealassessment',
            name='auto_parent_breakthroughs',
        ),
        migrations.RemoveField(
            model_name='dealassessment',
            name='auto_sota_comparison',
        ),
        migrations.RemoveField(
            model_name='dealassessment',
            name='auto_tags',
        ),
        migrations.RemoveField(
            model_name='dealassessment',
            name='auto_technical_risk',
        ),
        migrations.RemoveField(
            model_name='dealassessment',
            name='feasibility',
        ),
        migrations.RemoveField(
            model_name='dealassessment',
            name='parent_breakthroughs',
        ),
        migrations.RemoveField(
            model_name='dealassessment',
            name='sota_comparison',
        ),
        migrations.RemoveField(
            model_name='dealassessment',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='dealassessment',
            name='technical_risk',
        ),
        migrations.AlterField(
            model_name='dealassessment',
            name='auto_customer_traction',
            field=models.TextField(blank=True, editable=False, verbose_name='customer traction'),
        ),
    ]
