# Generated by Django 5.2.4 on 2025-08-11 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0028_dealassessment_remove_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='citation_count',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='citation count'),
        ),
    ]
