# Generated by Django 5.2.4 on 2025-08-11 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0029_add_paper_citation_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='deck',
            name='raw_text',
            field=models.TextField(blank=True, verbose_name='raw text'),
        ),
    ]
