# Generated by Django 5.2.4 on 2025-08-14 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0030_add_deck_raw_text'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deal',
            options={'verbose_name': 'Deal', 'verbose_name_plural': 'Deals'},
        ),
        migrations.AlterModelManagers(
            name='deal',
            managers=[],
        ),
    ]
