# Generated by Django 5.0 on 2024-01-12 19:47

import deals.files.storage
import django.contrib.postgres.fields
import django.core.files.storage
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='name')),
                ('company_name', models.CharField(blank=True, max_length=255, verbose_name='company name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='updated at')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_deals', related_query_name='created_deal', to=settings.AUTH_USER_MODEL, verbose_name='creator')),
            ],
            options={
                'verbose_name': 'Deal',
                'verbose_name_plural': 'Deals',
            },
        ),
        migrations.CreateModel(
            name='Deck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='title')),
                ('subtitle', models.CharField(blank=True, max_length=255, verbose_name='subtitle')),
                ('file', models.FileField(storage=django.core.files.storage.FileSystemStorage(), upload_to=deals.files.storage.deck_file_path, validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='file')),
                ('file_format', models.CharField(blank=True, choices=[('PDF', 'PDF')], default='PDF', max_length=255, verbose_name='file format')),
                ('ingestion_status', models.CharField(blank=True, choices=[('PENDING', 'Pending'), ('STARTED', 'Started processing'), ('SUCCESS', 'Successful'), ('FAILURE', 'Failed'), ('RETRY', 'Retrying'), ('REVOKED', 'Revoked')], default='PENDING', max_length=255, verbose_name='ingestion status')),
                ('text', models.TextField(blank=True, verbose_name='text')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='updated at')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_decks', related_query_name='created_deck', to=settings.AUTH_USER_MODEL, verbose_name='creator')),
                ('deal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decks', related_query_name='deck', to='deals.deal', verbose_name='deal')),
            ],
            options={
                'verbose_name': 'Deck',
                'verbose_name_plural': 'Decks',
            },
        ),
        migrations.CreateModel(
            name='DeckPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('page_number', models.IntegerField(blank=True, null=True, verbose_name='page number')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='name')),
                ('text', models.TextField(blank=True, verbose_name='text')),
                ('screenshot', models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(), upload_to=deals.files.storage.deck_page_screenshot_path, verbose_name='screenshot')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='updated at')),
                ('deck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', related_query_name='page', to='deals.deck', verbose_name='deck')),
            ],
            options={
                'verbose_name': 'Deck Page',
                'verbose_name_plural': 'Decks Pages',
            },
        ),
        migrations.CreateModel(
            name='DualUseSignal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('bg_color', models.CharField(blank=True, max_length=255, verbose_name='background color')),
                ('text_color', models.CharField(blank=True, max_length=255, verbose_name='text color')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='updated at')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_dual_use_signals', related_query_name='created_dual_use_signal', to=settings.AUTH_USER_MODEL, verbose_name='creator')),
            ],
            options={
                'verbose_name': 'Dual use signal',
                'verbose_name_plural': 'Dual use signals',
            },
        ),
        migrations.AddField(
            model_name='deal',
            name='dual_use_signals',
            field=models.ManyToManyField(blank=True, related_name='deals', related_query_name='deal', to='deals.dualusesignal', verbose_name='dual use signals'),
        ),
        migrations.CreateModel(
            name='FounderSignal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('bg_color', models.CharField(blank=True, max_length=255, verbose_name='background color')),
                ('text_color', models.CharField(blank=True, max_length=255, verbose_name='text color')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='updated at')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_founder_signals', related_query_name='created_founder_signal', to=settings.AUTH_USER_MODEL, verbose_name='creator')),
            ],
            options={
                'verbose_name': 'Founder signal',
                'verbose_name_plural': 'Founders signals',
            },
        ),
        migrations.AddField(
            model_name='deal',
            name='founder_signals',
            field=models.ManyToManyField(blank=True, related_name='deals', related_query_name='deal', to='deals.foundersignal', verbose_name='founder signals'),
        ),
        migrations.CreateModel(
            name='FundingRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='name/stage')),
                ('date', models.DateField(blank=True, null=True, verbose_name='date')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('target_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='target amount (USD)')),
                ('raised_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='raised amount (USD)')),
                ('investors_names', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, size=None, verbose_name='investor names')),
                ('is_active', models.BooleanField(blank=True, default=True, verbose_name='is active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='updated at')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_funding_rounds', related_query_name='created_funding_round', to=settings.AUTH_USER_MODEL, verbose_name='creator')),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funding_rounds', related_query_name='funding_round', to='deals.deal', verbose_name='deal')),
            ],
            options={
                'verbose_name': 'Funding Round',
                'verbose_name_plural': 'Funding Rounds',
            },
        ),
        migrations.CreateModel(
            name='Grant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='name')),
                ('date', models.DateField(blank=True, null=True, verbose_name='date')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('granting_agency', models.CharField(blank=True, max_length=255, verbose_name='granting agency')),
                ('obligated_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='obligated amount (USD)')),
                ('potential_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='obligated amount (USD)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='updated at')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_grants', related_query_name='created_grant', to=settings.AUTH_USER_MODEL, verbose_name='creator')),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grants', related_query_name='grant', to='deals.deal', verbose_name='deal')),
            ],
            options={
                'verbose_name': 'Grant',
                'verbose_name_plural': 'Grants',
            },
        ),
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('is_core', models.BooleanField(default=False, verbose_name='core')),
                ('bg_color', models.CharField(blank=True, max_length=255, verbose_name='background color')),
                ('text_color', models.CharField(blank=True, max_length=255, verbose_name='text color')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='updated at')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_industries', related_query_name='created_industry', to=settings.AUTH_USER_MODEL, verbose_name='creator')),
            ],
            options={
                'verbose_name': 'Industry',
                'verbose_name_plural': 'Industries',
            },
        ),
        migrations.AddField(
            model_name='deal',
            name='industries',
            field=models.ManyToManyField(blank=True, related_name='deals', related_query_name='deal', to='deals.industry', verbose_name='industries'),
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('military_or_govt_background', models.CharField(blank=True, max_length=255, verbose_name='government or military background')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='updated at')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_staffs', related_query_name='created_staff', to=settings.AUTH_USER_MODEL, verbose_name='creator')),
            ],
            options={
                'verbose_name': 'Staff',
                'verbose_name_plural': 'Staffs',
            },
        ),
        migrations.CreateModel(
            name='Enrolment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='title')),
                ('is_founder', models.BooleanField(blank=True, default=False, verbose_name='is founder')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='updated at')),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deals.deal', verbose_name='deal')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deals.staff', verbose_name='staff')),
            ],
        ),
        migrations.AddField(
            model_name='deal',
            name='staffs',
            field=models.ManyToManyField(blank=True, related_name='deals', related_query_name='deal', through='deals.Enrolment', to='deals.staff', verbose_name='staffs'),
        ),
    ]
