# Generated by Django 5.0 on 2024-01-13 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='sent_to_affinity',
            field=models.BooleanField(blank=True, null=True, verbose_name='sent to affinity'),
        ),
    ]
