# Generated by Django 5.0 on 2024-01-17 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0004_deal_search_vector_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='deck',
            name='ingestion_task_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, verbose_name='ingestion task ID'),
        ),
    ]
