# Generated by Django 5.0 on 2024-01-29 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0005_deck_ingestion_task_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='deck',
            name='extras',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='extras'),
        ),
    ]
