# Generated by Django 5.0 on 2024-01-30 09:00

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0006_deck_extras'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='customers_names',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, size=None, verbose_name='customers names'),
        ),
        migrations.AddField(
            model_name='deal',
            name='partners_names',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, size=None, verbose_name='partners names'),
        ),
        migrations.AddField(
            model_name='deal',
            name='stage',
            field=models.CharField(blank=True, choices=[('pre-seed', 'pre-seed'), ('seed', 'seed'), ('seed+', 'seed+'), ('series-a', 'series A'), ('series-b', 'series B'), ('series-c', 'series C'), ('beyond-series-c', 'beyond series C')], max_length=255, verbose_name='stage'),
        ),
        migrations.AddField(
            model_name='deal',
            name='website',
            field=models.URLField(blank=True, verbose_name='website'),
        ),
    ]
