# Generated by Django 5.0 on 2024-01-30 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0007_deal_add_customers_partners_stage_website'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fundinground',
            old_name='name',
            new_name='stage',
        ),
    ]
