# Generated by Django 5.0 on 2024-01-30 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0008_rename_name_fundinground_stage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundinground',
            name='stage',
            field=models.CharField(blank=True, choices=[('pre-seed', 'pre-seed'), ('seed', 'seed'), ('seed+', 'seed+'), ('series-a', 'series A'), ('series-b', 'series B'), ('series-c', 'series C'), ('beyond-series-c', 'beyond series C')], max_length=255, verbose_name='name/stage'),
        ),
    ]
