# Generated by Django 5.0 on 2024-02-02 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0009_alter_fundinground_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='auto_cons',
            field=models.TextField(blank=True, verbose_name='cons (automated)'),
        ),
        migrations.AddField(
            model_name='deal',
            name='auto_investment_rationale',
            field=models.TextField(blank=True, verbose_name='investment rationale (automated)'),
        ),
        migrations.AddField(
            model_name='deal',
            name='auto_pros',
            field=models.TextField(blank=True, verbose_name='pros (automated)'),
        ),
        migrations.AddField(
            model_name='deal',
            name='cons',
            field=models.TextField(blank=True, verbose_name='cons'),
        ),
        migrations.AddField(
            model_name='deal',
            name='investment_rationale',
            field=models.TextField(blank=True, verbose_name='investment rationale'),
        ),
        migrations.AddField(
            model_name='deal',
            name='pros',
            field=models.TextField(blank=True, verbose_name='pros'),
        ),
    ]
