# Generated by Django 5.0 on 2024-02-12 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0010_deal_pros_cons_investment_rationale'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deal',
            old_name='auto_investment_rationale',
            new_name='auto_recommendation',
        ),
    ]
