# Generated by Django 5.0 on 2024-02-12 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0011_rename_auto_investment_rationale_deal_auto_recommendation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='auto_recommendation',
            field=models.TextField(blank=True, verbose_name='recommendation (automated)'),
        ),
    ]
