# Generated by Django 5.0 on 2024-02-12 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0012_alter_deal_auto_recommendation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deck',
            name='extras',
            field=models.JSONField(blank=True, default=dict, verbose_name='extras'),
        ),
    ]
