# Generated by Django 5.0 on 2024-02-14 11:46

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0013_alter_deck_extras'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='address_line_1',
            field=models.CharField(blank=True, max_length=255, verbose_name='address line 1'),
        ),
        migrations.AddField(
            model_name='deal',
            name='address_line_2',
            field=models.CharField(blank=True, max_length=255, verbose_name='address line 2'),
        ),
        migrations.AddField(
            model_name='deal',
            name='city',
            field=models.CharField(blank=True, max_length=255, verbose_name='city'),
        ),
        migrations.AddField(
            model_name='deal',
            name='company_duns',
            field=models.IntegerField(blank=True, null=True, verbose_name='D-U-N-S number'),
        ),
        migrations.AddField(
            model_name='deal',
            name='company_nid',
            field=models.IntegerField(blank=True, null=True, verbose_name='Company NID'),
        ),
        migrations.AddField(
            model_name='deal',
            name='postal_code',
            field=models.CharField(blank=True, max_length=255, verbose_name='postal/zip code'),
        ),
        migrations.AddField(
            model_name='deal',
            name='state_code',
            field=models.CharField(blank=True, max_length=255, verbose_name='state code'),
        ),
        migrations.AddField(
            model_name='deal',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, size=None, verbose_name='tags'),
        ),
    ]
