# Generated by Django 5.0 on 2024-02-14 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0014_deal_sbir_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='grant',
            name='extras',
            field=models.JSONField(blank=True, default=dict, verbose_name='extras'),
        ),
    ]
