# Generated by Django 5.0 on 2024-02-14 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0015_grant_extras'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grant',
            name='potential_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='potential amount (USD)'),
        ),
    ]
