# Generated by Django 5.0 on 2024-02-14 16:35

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0016_alter_grant_potential_amount'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='grant',
            name='award_month',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='award month'),
        ),
        migrations.AddField(
            model_name='grant',
            name='award_year',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='award year'),
        ),
        migrations.AddIndex(
            model_name='grant',
            index=models.Index(fields=['award_year', 'award_month'], name='award_year_month_idx'),
        ),
    ]
