# Generated by Django 5.0 on 2024-02-14 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0017_grant_award_month_grant_award_year_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grant',
            old_name='date',
            new_name='award_date',
        ),
    ]
