# Generated by Django 5.0 on 2024-02-14 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0018_rename_date_grant_award_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grant',
            name='award_date',
            field=models.DateField(blank=True, null=True, verbose_name='award date'),
        ),
    ]
