# Generated by Django 5.0 on 2024-02-18 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0020_dualusesignal_unique_name_lower'),
    ]

    operations = [
        migrations.AddField(
            model_name='grant',
            name='award_url',
            field=models.URLField(blank=True, verbose_name='award URL'),
        ),
        migrations.AddField(
            model_name='grant',
            name='branch',
            field=models.CharField(blank=True, max_length=255, verbose_name='branch'),
        ),
        migrations.AddField(
            model_name='grant',
            name='phase',
            field=models.CharField(blank=True, max_length=255, verbose_name='phase'),
        ),
        migrations.AddField(
            model_name='grant',
            name='program_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='program name'),
        ),
    ]
