# Generated by Django 5.0 on 2024-02-21 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0021_grant_award_url_branch_phase_program_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='affinity_organization_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='affinity organization ID'),
        ),
    ]
