# Generated by Django 5.0 on 2024-02-23 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0022_deal_affinity_organization_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='business_model',
            field=models.TextField(blank=True, verbose_name='business model'),
        ),
        migrations.AddField(
            model_name='deal',
            name='competition',
            field=models.TextField(blank=True, verbose_name='competition'),
        ),
        migrations.AddField(
            model_name='deal',
            name='intellectual_property',
            field=models.TextField(blank=True, verbose_name='intellectual property'),
        ),
        migrations.AddField(
            model_name='deal',
            name='market_sizing',
            field=models.TextField(blank=True, verbose_name='market_sizing'),
        ),
        migrations.AddField(
            model_name='deal',
            name='problem',
            field=models.TextField(blank=True, verbose_name='problem'),
        ),
        migrations.AddField(
            model_name='deal',
            name='recommendation',
            field=models.CharField(blank=True, choices=[('prep to call', 'prep to call'), ('prep to pass', 'prep to pass')], max_length=50, verbose_name='recommendation'),
        ),
        migrations.AddField(
            model_name='deal',
            name='solution',
            field=models.TextField(blank=True, verbose_name='solution'),
        ),
        migrations.AddField(
            model_name='deal',
            name='thesis_fit',
            field=models.TextField(blank=True, verbose_name='thesis fit'),
        ),
        migrations.AddField(
            model_name='deal',
            name='traction',
            field=models.TextField(blank=True, verbose_name='traction'),
        ),
    ]
