# Generated by Django 5.0 on 2024-02-23 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0023_deal_additional_assesment_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='auto_business_model',
            field=models.TextField(blank=True, verbose_name='business model (automated)'),
        ),
        migrations.AddField(
            model_name='deal',
            name='auto_competition',
            field=models.TextField(blank=True, verbose_name='competition (automated)'),
        ),
        migrations.AddField(
            model_name='deal',
            name='auto_intellectual_property',
            field=models.TextField(blank=True, verbose_name='intellectual property (automated)'),
        ),
        migrations.AddField(
            model_name='deal',
            name='auto_investment_rationale',
            field=models.TextField(blank=True, verbose_name='investment rationale (automated)'),
        ),
        migrations.AddField(
            model_name='deal',
            name='auto_market_sizing',
            field=models.TextField(blank=True, verbose_name='market_sizing (automated)'),
        ),
        migrations.AddField(
            model_name='deal',
            name='auto_problem',
            field=models.TextField(blank=True, verbose_name='problem (automated)'),
        ),
        migrations.AddField(
            model_name='deal',
            name='auto_solution',
            field=models.TextField(blank=True, verbose_name='solution (automated)'),
        ),
        migrations.AddField(
            model_name='deal',
            name='auto_thesis_fit',
            field=models.TextField(blank=True, verbose_name='thesis fit (automated)'),
        ),
        migrations.AddField(
            model_name='deal',
            name='auto_traction',
            field=models.TextField(blank=True, verbose_name='traction (automated)'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='auto_recommendation',
            field=models.CharField(blank=True, choices=[('prep to call', 'prep to call'), ('prep to pass', 'prep to pass')], max_length=50, verbose_name='recommendation (automated)'),
        ),
    ]
