# Generated by Django 5.0 on 2024-02-23 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0024_deal_additional_auto_assesment_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='description',
            field=models.TextField(blank=True, verbose_name='product description'),
        ),
    ]
