# Generated by Django 5.0.2 on 2024-02-26 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0025_alter_deal_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='auto_description',
            field=models.TextField(blank=True, verbose_name='product description (automated)'),
        ),
    ]
