# Generated by Django 5.0.2 on 2024-02-29 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0026_deal_auto_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='country_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='country name'),
        ),
        migrations.AddField(
            model_name='staff',
            name='education',
            field=models.JSONField(blank=True, db_default=models.Value([]), default=list, verbose_name='education'),
        ),
        migrations.AddField(
            model_name='staff',
            name='experience',
            field=models.JSONField(blank=True, db_default=models.Value([]), default=list, verbose_name='experience'),
        ),
        migrations.AddField(
            model_name='staff',
            name='linkedin_url',
            field=models.URLField(blank=True, null=True, verbose_name='Linkedin URL'),
        ),
        migrations.AddField(
            model_name='staff',
            name='location',
            field=models.CharField(blank=True, max_length=255, verbose_name='location'),
        ),
    ]
