# Generated by Django 5.0.2 on 2024-02-29 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0027_staff_country_name_staff_education_staff_experience_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enrolment',
            options={'verbose_name': 'Enrolment', 'verbose_name_plural': 'Enrolments'},
        ),
        migrations.AlterField(
            model_name='enrolment',
            name='deal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrolments', related_query_name='enrolment', to='deals.deal', verbose_name='deal'),
        ),
        migrations.AlterField(
            model_name='enrolment',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrolments', related_query_name='enrolment', to='deals.staff', verbose_name='staff'),
        ),
    ]
