# Generated by Django 5.0.2 on 2024-02-29 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0028_alter_enrolment_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff',
            old_name='education',
            new_name='education_collection',
        ),
        migrations.RenameField(
            model_name='staff',
            old_name='experience',
            new_name='experience_collection',
        ),
    ]
