# Generated by Django 5.0.2 on 2024-03-04 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0029_rename_staff_education_and_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='market_sizing',
            field=models.TextField(blank=True, verbose_name='market sizing'),
        ),
    ]
