# Generated by Django 5.0.2 on 2024-03-04 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0030_alter_deal_market_sizing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='auto_description',
            field=models.TextField(blank=True, verbose_name='description (automated)'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='auto_solution',
            field=models.TextField(blank=True, verbose_name='product/solution (automated)'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='description',
            field=models.TextField(blank=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='solution',
            field=models.TextField(blank=True, verbose_name='product/solution'),
        ),
    ]
