# Generated by Django 5.0.2 on 2024-03-06 16:21

import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0031_alter_deal_description_and_solution_labels'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='deck',
            managers=[
                ('from_mailbox', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='deck',
            name='is_from_mailbox',
            field=models.BooleanField(blank=True, db_index=True, default=False, verbose_name='is from mailbox'),
        ),
    ]
