# Generated by Django 5.0.2 on 2024-03-07 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0032_add_deck_is_from_mailbox'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='deck',
            managers=[
            ],
        ),
    ]
