# Generated by Django 5.0.2 on 2024-04-12 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0033_alter_deck_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='auto_quality_percentile',
            field=models.CharField(blank=True, choices=[('top 1%', 'extraordinary'), ('top 5%', 'very promising'), ('top 10%', 'potentially interesting'), ('top 20%', 'average'), ('top 50%', 'poor'), ('top 80%', 'top 80%')], max_length=50, verbose_name='quality percentile (automated)'),
        ),
    ]
