# Generated by Django 5.0.2 on 2024-04-12 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0034_deal_auto_quality_percentile'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='has_veteran_founder',
            field=models.BooleanField(blank=True, null=True, verbose_name='has veteran founder'),
        ),
    ]
