# Generated by Django 5.0.2 on 2024-04-15 20:56

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0035_deal_has_veteran_founder'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='funding_raised',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='funding raised (USD)'),
        ),
        migrations.AddField(
            model_name='deal',
            name='funding_target',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='funding target (USD)'),
        ),
        migrations.AddField(
            model_name='deal',
            name='investors_names',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, size=None, verbose_name='investor names'),
        ),
    ]
