# Generated by Django 5.0.2 on 2024-04-22 21:17

import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0036_deal_funding_target_raised_investors_names'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicalStudy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('nct_id', models.CharField(blank=True, db_index=True, help_text='National Clinical Trial (NCT) ID given to each clinical study upon registration at ClinicalTrials.gov', max_length=255, verbose_name='NCT ID')),
                ('title', models.CharField(max_length=512, verbose_name='title')),
                ('lead_sponsor_name', models.CharField(blank=True, max_length=255, verbose_name='lead sponsor name')),
                ('collaborators_names', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, size=None, verbose_name='collaborators names')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('start_date_str', models.CharField(blank=True, max_length=255, verbose_name='start date')),
                ('completion_date_str', models.CharField(blank=True, max_length=255, verbose_name='start date')),
                ('status', models.CharField(blank=True, choices=[('ACTIVE_NOT_RECRUITING', 'Active, not recruiting'), ('COMPLETED', 'Completed'), ('ENROLLING_BY_INVITATION', 'Enrolling by invitation'), ('NOT_YET_RECRUITING', 'Not yet recruiting'), ('RECRUITING', 'Recruiting'), ('SUSPENDED', 'Suspended'), ('TERMINATED', 'Terminated'), ('WITHDRAWN', 'Withdrawn'), ('AVAILABLE', 'Available'), ('NO_LONGER_AVAILABLE', 'No longer available'), ('TEMPORARILY_NOT_AVAILABLE', 'Temporarily not available'), ('APPROVED_FOR_MARKETING', 'Approved for marketing'), ('WITHHELD', 'Withheld'), ('UNKNOWN', 'Unknown status')], max_length=255, verbose_name='status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='updated at')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_clinical_studies', related_query_name='created_clinical_study', to=settings.AUTH_USER_MODEL, verbose_name='creator')),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clinical_studies', related_query_name='clinical_study', to='deals.deal', verbose_name='deal')),
            ],
            options={
                'verbose_name': 'Clinical Study',
                'verbose_name_plural': 'Clinical Studies',
            },
        ),
    ]
