# Generated by Django 5.0.2 on 2024-04-22 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0037_clinicalstudy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinicalstudy',
            name='completion_date_str',
            field=models.CharField(blank=True, db_index=True, max_length=255, verbose_name='start date'),
        ),
        migrations.AlterField(
            model_name='clinicalstudy',
            name='start_date_str',
            field=models.CharField(blank=True, db_index=True, max_length=255, verbose_name='start date'),
        ),
    ]
