# Generated by Django 5.0.2 on 2024-04-29 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0039_deal_quality_percentile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='auto_quality_percentile',
            field=models.CharField(blank=True, choices=[('top 1%', 'most interesting'), ('top 5%', 'very interesting'), ('top 10%', 'interesting'), ('top 20%', 'potentially interesting'), ('top 50%', 'not interesting')], max_length=50, verbose_name='quality percentile (automated)'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='quality_percentile',
            field=models.CharField(blank=True, choices=[('top 1%', 'most interesting'), ('top 5%', 'very interesting'), ('top 10%', 'interesting'), ('top 20%', 'potentially interesting'), ('top 50%', 'not interesting')], max_length=50, verbose_name='quality percentile'),
        ),
    ]
