# Generated by Django 5.0.2 on 2024-10-16 09:37

import deals.files.storage
import django.core.files.storage
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0040_alter_deal_quality_percentile_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deck',
            name='file',
            field=models.FileField(max_length=255, storage=django.core.files.storage.FileSystemStorage(), upload_to=deals.files.storage.deck_file_path, validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='file'),
        ),
    ]
