# Generated by Django 5.0.2 on 2024-10-24 09:12
from django.db import migrations, models

from aindex.utils import us_state_code_name, us_state_name_code


def us_state_code_to_name(apps, schema_editor):
    """Convert state codes to state names"""
    Deal = apps.get_model('deals', 'Deal')
    db_alias = schema_editor.connection.alias

    for deal in Deal.objects.using(db_alias).exclude(state='').iterator():
        deal.state = us_state_code_name.get(deal.state, deal.state)
        deal.save()


def us_state_name_to_code(apps, schema_editor):
    """Convert state names to state codes"""
    Deal = apps.get_model('deals', 'Deal')
    db_alias = schema_editor.connection.alias

    for deal in Deal.objects.using(db_alias).exclude(state='').iterator():
        deal.state = us_state_name_code.get(deal.state, deal.state)
        deal.save()


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0041_alter_deck_file_max_length'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deal',
            old_name='state_code',
            new_name='state',
        ),
        migrations.AlterField(
            model_name='deal',
            name='state',
            field=models.CharField(blank=True, max_length=255, verbose_name='state'),
        ),
        migrations.RunPython(
            code=us_state_code_to_name,
            reverse_code=us_state_name_to_code
        ),
    ]
