# Generated by Django 5.0.2 on 2024-12-04 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0042_rename_state_code_deal_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grant',
            name='award_url',
        ),
        migrations.AddField(
            model_name='grant',
            name='sbir_id',
            field=models.CharField(blank=True, max_length=255, verbose_name='SBIR award ID'),
        ),
    ]
