# Generated by Django 5.0.2 on 2025-01-17 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0045_misseddeal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='misseddeal',
            name='cb_url',
            field=models.URLField(blank=True, default='', verbose_name='crunchbase URL'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='misseddeal',
            name='website',
            field=models.URLField(blank=True, default='', verbose_name='website'),
            preserve_default=False,
        ),
    ]
