# Generated by Django 5.0.2 on 2025-01-23 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0046_alter_misseddeal_cb_url_alter_misseddeal_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='misseddeal',
            name='extras',
            field=models.JSONField(blank=True, default=dict, verbose_name='extras'),
        ),
    ]
