# Generated by Django 5.0.2 on 2025-01-23 10:16

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0048_rename_postal_code_misseddeal_hq_postal_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='misseddeal',
            name='hq_regions_names',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=64), blank=True, default=list, size=None, verbose_name='HQ regions'),
        ),
    ]
