# Generated by Django 5.0.2 on 2025-01-23 12:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0021_company_hq_regions_names'),
        ('deals', '0049_misseddeal_hq_regions_names'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='misseddeal',
            name='last_funding_month',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='last funding month'),
        ),
        migrations.AddField(
            model_name='misseddeal',
            name='last_funding_year',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='last funding year'),
        ),
        migrations.AddConstraint(
            model_name='misseddeal',
            constraint=models.UniqueConstraint(fields=('company', 'last_funding_year', 'last_funding_month'), name='deals_misseddeal_company_last_funding_year_month_key'),
        ),
    ]
