# Generated by Django 5.0.2 on 2025-01-24 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0050_add_month_unique_constraint'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='auto_confidence',
            field=models.CharField(blank=True, choices=[('high', 'High'), ('low', 'Low')], max_length=50, verbose_name='confidence (automated)'),
        ),
        migrations.AddField(
            model_name='deal',
            name='auto_non_numeric_score',
            field=models.CharField(blank=True, choices=[('excellent', 'Excellent'), ('good', 'Good'), ('average', 'Average'), ('below average', 'Below average')], max_length=50, verbose_name='non numeric score (automated)'),
        ),
        migrations.AddField(
            model_name='deal',
            name='auto_numeric_score',
            field=models.FloatField(blank=True, null=True, verbose_name='numeric score (automated)'),
        ),
    ]
