# Generated by Django 5.0.2 on 2025-02-05 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0051_add_deal_auto_numeric_score_auto_non_numeric_score_confidence'),
    ]

    operations = [
        migrations.AddField(
            model_name='misseddeal',
            name='was_in_deals',
            field=models.BooleanField(default=False, verbose_name='was in deals'),
        ),
    ]
