# Generated by Django 5.0.2 on 2025-02-05 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0022_company_extras'),
        ('deals', '0052_misseddeal_was_in_deals'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deals', related_query_name='deal', to='companies.company', verbose_name='company'),
        ),
    ]
