# Generated by Django 5.0.2 on 2025-03-13 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0053_alter_deal_company_related_names'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='auto_thesis_fit_score',
            field=models.FloatField(blank=True, null=True, verbose_name='thesis fit score (automated)'),
        ),
    ]
