# Generated by Django 5.1.8 on 2025-05-05 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0054_deal_auto_thesis_fit_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='processing_status',
            field=models.CharField(blank=True, choices=[('PENDING', 'Pending'), ('STARTED', 'Started processing'), ('SUCCESS', 'Successful'), ('FAILURE', 'Failed'), ('RETRY', 'Retrying'), ('REVOKED', 'Revoked')], max_length=128, verbose_name='processing status'),
        ),
    ]
