# Generated by Django 5.1.8 on 2025-06-02 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("deals", "0055_deal_processing_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="enrolment",
            name="deal",
        ),
        migrations.RemoveField(
            model_name="enrolment",
            name="staff",
        ),
        migrations.RemoveField(
            model_name="deal",
            name="staffs",
        ),
        migrations.RemoveField(
            model_name="grant",
            name="creator",
        ),
        migrations.RemoveField(
            model_name="grant",
            name="deal",
        ),
        migrations.RemoveField(
            model_name="staff",
            name="creator",
        ),
        migrations.DeleteModel(
            name="ClinicalStudy",
        ),
        migrations.DeleteModel(
            name="Enrolment",
        ),
        migrations.DeleteModel(
            name="Grant",
        ),
        migrations.DeleteModel(
            name="Staff",
        ),
    ]
