# Generated by Django 5.1.8 on 2025-06-16 12:08

import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("deals", "0056_remove_deprecated_models"),
    ]

    operations = [
        migrations.AddField(
            model_name="deal",
            name="country",
            field=django_countries.fields.CountryField(
                blank=True, max_length=2, verbose_name="country"
            ),
        ),
    ]
