default_industries_names = [
    'Advanced Materials',
    'Aerospace (Air)',
    'Aerospace (Space)',
    'Analytics',
    'Artificial Intelligence',
    'Augmented/Virtual Reality',
    'Automotive',
    'Biotechnology',
    'Blockchain',
    'Budgeting',
    'Business Processses',
    'CleanTech',
    'Collaboration',
    'Community Engagement',
    'Compliance',
    'Computation',
    'Computer Vision',
    'Cybersecurity',
    'Data Center',
    'Data Management',
    'Data Science',
    'Data Storage',
    'Defense',
    'Developer Tools',
    'Drones',
    'Elections',
    'Energy Tech',
    'Enterprise Software',
    'Fintech',
    'Geospatial',
    'Healthcare Administration',
    'Human Resources',
    'Identity Management',
    'Infrastructure',
    'IoT',
    'Law Enforcement',
    'Legal',
    'Manufacturing',
    'Medical Technology',
    'Microprocessors',
    'name',
    'Networking',
    'Performance Management',
    'Pharmaceuticals',
    'Physical Security',
    'Procurement/Contracts',
    'Public Safety',
    'Quantum Computation',
    'Research & Development',
    'Risk Management',
    'Robotics',
    'Satellite Communications',
    'Search',
    'Secure Communications',
    'Sensing',
    'Smart Cities',
    'Sustainability Tech',
    'Urban Planning',
    'Web Operations',
    'Wireless Networking',
]

default_deeptech_signals = [
    'Advanced Materials',
    'Artificial Intelligence & Machine Learning',
    'Augmented Reality (AR) and Virtual Reality (VR)',
    'Bio-derived Energy Storage',
    'Computing chips',
    'Cybersecurity',
    'Directed Energy',
    'Drones and Autonomous Vehicles',
    'Energy and Resource Management',
    'Internet of Things (IoT)',
    'Quantum Computing',
    'Renewable Energy Generation & Storage',
    'Robotic Process Automation (RPA)',
    'Secure Edge/IoT Computing',
    'Voice and Natural Language Processing (NLP)',
    'Wearable Technology',
]

default_strategic_domain_signals = [
    'Aerospace',
    'Analytics and Decision Support',
    'Biodefense Detection & Containment',
    'Chips',
    'Digital Identity and Access Management',
    'Electronic Health Records',
    'Geospatial Analysis and Mapping',
    'Maritime',
    'Microelectronics Quantifiable Assurance',
    'Supply Chain Resilience',
    'Sustainability',
    'Training & Workforce Development',
    'Trauma-Oriented Healthcare',
]
