# Generated by Django 5.2.4 on 2025-07-18 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='affinity_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='affinity organization ID'),
        ),
    ]
