# Generated by Django 5.2.4 on 2025-07-21 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_company_affinity_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='founding',
            old_name='company_id',
            new_name='company',
        ),
        migrations.RenameField(
            model_name='founding',
            old_name='founder_id',
            new_name='founder',
        ),
    ]
