# Generated by Django 5.2.4 on 2025-07-21 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_rename_founding_company_and_founder_ids'),
    ]

    operations = [
        migrations.AddField(
            model_name='founding',
            name='title',
            field=models.CharField(blank=True, max_length=255, verbose_name='title'),
        ),
    ]
