# Generated by Django 5.2.4 on 2025-07-21 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_founding_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='founding',
            old_name='past_significant_employment',
            new_name='past_significant_employments',
        ),
    ]
