# Generated by Django 5.2.4 on 2025-07-22 14:04

import django.db.models.deletion
import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0006_rename_past_significant_employment_founding_past_significant_employments'),
        ('socialgraph', '0003_add_unique_profile_linkedin_url_and_no_blank_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advisor',
            fields=[
                (
                    'profile_ptr',
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to='socialgraph.profile',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Advisor',
                'verbose_name_plural': 'Advisors',
            },
            bases=('socialgraph.profile',),
        ),
        migrations.CreateModel(
            name='CompanyAdvisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'created_at',
                    models.DateTimeField(
                        auto_now_add=True,
                        db_default=django.db.models.functions.datetime.Now(),
                        verbose_name='created at',
                    ),
                ),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='updated at')),
                (
                    'advisor',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='company_advisors',
                        related_query_name='company_advisor',
                        to='companies.advisor',
                        verbose_name='advisor',
                    ),
                ),
                (
                    'company',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='company_advisors',
                        related_query_name='company_advisor',
                        to='companies.company',
                        verbose_name='company',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Company advisor',
                'verbose_name_plural': 'Company advisors',
            },
        ),
        migrations.AddField(
            model_name='company',
            name='advisors',
            field=models.ManyToManyField(
                blank=True,
                related_name='companies',
                related_query_name='company',
                through='companies.CompanyAdvisor',
                to='companies.advisor',
                verbose_name='advisors',
            ),
        ),
    ]
