# Generated by Django 5.2.4 on 2025-07-29 18:18

import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0007_add_company_advisors'),
    ]

    operations = [
        migrations.AddField(
            model_name='founding',
            name='created_at',
            field=models.DateTimeField(
                auto_now_add=True, db_default=django.db.models.functions.datetime.Now(), verbose_name='created at'
            ),
        ),
        migrations.AddField(
            model_name='founding',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='updated at'),
        ),
    ]
