# Generated by Django 5.1.8 on 2025-06-17 22:31

import django.contrib.postgres.fields
import django.core.files.storage
import django.core.validators
import django.db.models.deletion
import django.db.models.functions.datetime
import librarain.files
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="UUID",
                    ),
                ),
                (
                    "name",
                    models.CharField(blank=True, max_length=255, verbose_name="name"),
                ),
                (
                    "semantic_scholar_id",
                    models.SlugField(blank=True, verbose_name="semantic scholar ID"),
                ),
                (
                    "arvix_id",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="arXiv ID"
                    ),
                ),
                (
                    "citation_count",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="citation count"
                    ),
                ),
                (
                    "paper_count",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="paper count"
                    ),
                ),
                (
                    "h_index",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="h-index"
                    ),
                ),
                (
                    "affiliations",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=255),
                        blank=True,
                        default=list,
                        size=None,
                        verbose_name="affiliations",
                    ),
                ),
                (
                    "extras",
                    models.JSONField(blank=True, default=dict, verbose_name="extras"),
                ),
            ],
            options={
                "verbose_name": "Author",
                "verbose_name_plural": "Authors",
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="UUID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="name")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="description"),
                ),
                (
                    "code",
                    models.SlugField(blank=True, unique=True, verbose_name="code"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_default=django.db.models.functions.datetime.Now(),
                        verbose_name="created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, null=True, verbose_name="updated at"
                    ),
                ),
                (
                    "extras",
                    models.JSONField(blank=True, default=dict, verbose_name="extras"),
                ),
            ],
            options={
                "verbose_name": "Category",
                "verbose_name_plural": "Categories",
            },
        ),
        migrations.CreateModel(
            name="DocumentType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="UUID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="name")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="description"),
                ),
                (
                    "code",
                    models.SlugField(blank=True, unique=True, verbose_name="code"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_default=django.db.models.functions.datetime.Now(),
                        verbose_name="created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, null=True, verbose_name="updated at"
                    ),
                ),
                (
                    "extras",
                    models.JSONField(blank=True, default=dict, verbose_name="extras"),
                ),
            ],
            options={
                "verbose_name": "Document Type",
                "verbose_name_plural": "Document Types",
            },
        ),
        migrations.CreateModel(
            name="Source",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="UUID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="name")),
                (
                    "code",
                    models.SlugField(blank=True, unique=True, verbose_name="code"),
                ),
                ("website", models.URLField(blank=True, verbose_name="website URL")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="description"),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=librarain.files.source_image_path,
                        verbose_name="image or logo",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_default=django.db.models.functions.datetime.Now(),
                        verbose_name="created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, null=True, verbose_name="updated at"
                    ),
                ),
                (
                    "extras",
                    models.JSONField(blank=True, default=dict, verbose_name="extras"),
                ),
            ],
            options={
                "verbose_name": "Source",
                "verbose_name_plural": "Sources",
            },
        ),
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="UUID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="title")),
                ("abstract", models.TextField(blank=True, verbose_name="abstract")),
                ("text", models.TextField(blank=True, verbose_name="text")),
                (
                    "src_id",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="external ID"
                    ),
                ),
                ("src_url", models.URLField(blank=True, verbose_name="external URL")),
                (
                    "src_download_url",
                    models.URLField(blank=True, verbose_name="external download URL"),
                ),
                (
                    "semantic_scholar_id",
                    models.SlugField(blank=True, verbose_name="semantic scholar ID"),
                ),
                (
                    "arvix_id",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="arXiv ID"
                    ),
                ),
                (
                    "publication_year",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="year published"
                    ),
                ),
                (
                    "publication_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="date published"
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        max_length=255,
                        storage=django.core.files.storage.FileSystemStorage(),
                        upload_to=librarain.files.document_file_path,
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                [
                                    "doc",
                                    "docx",
                                    "html",
                                    "md",
                                    "odt",
                                    "pdf",
                                    "rst",
                                    "tex",
                                    "txt",
                                ]
                            )
                        ],
                        verbose_name="file",
                    ),
                ),
                (
                    "tags",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=255),
                        blank=True,
                        default=list,
                        size=None,
                        verbose_name="tags",
                    ),
                ),
                ("license", models.CharField(max_length=255, verbose_name="license")),
                (
                    "extras",
                    models.JSONField(blank=True, default=dict, verbose_name="extras"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_default=django.db.models.functions.datetime.Now(),
                        verbose_name="created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, null=True, verbose_name="updated at"
                    ),
                ),
                (
                    "authors",
                    models.ManyToManyField(
                        blank=True,
                        related_name="documents",
                        related_query_name="document",
                        to="librarain.author",
                        verbose_name="authors",
                    ),
                ),
                (
                    "categories",
                    models.ManyToManyField(
                        blank=True,
                        related_name="document",
                        related_query_name="documents",
                        to="librarain.category",
                        verbose_name="categories",
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_documents",
                        related_query_name="created_document",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="creator",
                    ),
                ),
                (
                    "document_types",
                    models.ManyToManyField(
                        blank=True,
                        related_name="document",
                        related_query_name="documents",
                        to="librarain.documenttype",
                        verbose_name="document type",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="document",
                        related_query_name="documents",
                        to="librarain.source",
                        verbose_name="source",
                    ),
                ),
            ],
            options={
                "verbose_name": "Document",
                "verbose_name_plural": "Documents",
            },
        ),
        migrations.CreateModel(
            name="Citation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "year",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="year"
                    ),
                ),
                (
                    "extras",
                    models.JSONField(blank=True, default=dict, verbose_name="extras"),
                ),
                (
                    "cited_document",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="citations",
                        related_query_name="citation",
                        to="librarain.document",
                        verbose_name="cited document",
                    ),
                ),
                (
                    "citing_document",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="references",
                        related_query_name="reference",
                        to="librarain.document",
                        verbose_name="citing document",
                    ),
                ),
            ],
            options={
                "verbose_name": "Citation",
                "verbose_name_plural": "Citations",
            },
        ),
    ]
