# Generated by Django 5.1.8 on 2025-06-18 19:35

from django.db import migrations
from pgvector.django import VectorExtension


class Migration(migrations.Migration):

    dependencies = [
        ("librarain", "0001_initial"),
    ]

    operations = [
        VectorExtension(),
    ]
