# Generated by Django 5.1.8 on 2025-06-18 20:59

import pgvector.django.indexes
import pgvector.django.vector
from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("librarain", "0002_create_pgvector"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="embedding",
            field=pgvector.django.vector.VectorField(
                blank=True, dimensions=768, null=True, verbose_name="embedding"
            ),
        ),
        migrations.AddIndex(
            model_name="document",
            index=pgvector.django.indexes.HnswIndex(
                ef_construction=64,
                fields=["embedding"],
                m=16,
                name="librarain_doc_embedding_idx",
                opclasses=["vector_l2_ops"],
            ),
        ),
    ]
