# Generated by Django 5.1.8 on 2025-06-18 21:45

import django.db.models.deletion
import django.db.models.functions.datetime
import pgvector.django.indexes
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("librarain", "0003_add_document_embedding"),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField(blank=True, verbose_name="text")),
                (
                    "page_number",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="page number"
                    ),
                ),
                (
                    "index_number",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="index number"
                    ),
                ),
                (
                    "embedding",
                    pgvector.django.vector.VectorField(
                        blank=True, dimensions=768, null=True, verbose_name="embedding"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_default=django.db.models.functions.datetime.Now(),
                        verbose_name="created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, null=True, verbose_name="updated at"
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sections",
                        related_query_name="section",
                        to="librarain.document",
                        verbose_name="document",
                    ),
                ),
            ],
            options={
                "verbose_name": "Document Section",
                "verbose_name_plural": "Documents Sections",
                "indexes": [
                    pgvector.django.indexes.HnswIndex(
                        ef_construction=64,
                        fields=["embedding"],
                        m=16,
                        name="librarain_docsec_embedding_idx",
                        opclasses=["vector_l2_ops"],
                    )
                ],
            },
        ),
    ]
