# Generated by Django 5.1.8 on 2025-06-19 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('librarain', '0005_semanticscholarsearch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='arvix_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='arXiv ID'),
        ),
        migrations.AlterField(
            model_name='document',
            name='semantic_scholar_id',
            field=models.SlugField(blank=True, null=True, unique=True, verbose_name='semantic scholar ID'),
        ),
    ]
