# Generated by Django 5.1.8 on 2025-06-19 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('librarain', '0007_make_unique_author_arvix_and_semanticsholar_ids'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='tldr',
            field=models.TextField(blank=True, help_text='auto-generated short summary of the paper.', verbose_name='tl;dr'),
        ),
    ]
