# Generated by Django 5.1.8 on 2025-06-19 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('librarain', '0008_document_tldr'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='arvix_id',
            new_name='arxiv_id',
        ),
        migrations.RenameField(
            model_name='document',
            old_name='arvix_id',
            new_name='arxiv_id',
        ),
    ]
