# Generated by Django 5.1.8 on 2025-06-20 10:22

import django.db.models.deletion
import django.db.models.functions.datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('librarain', '0009_rename_typo_rxiv'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArxivSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('query', models.CharField(blank=True, help_text='a text search query.', max_length=255, verbose_name='query')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='title')),
                ('author', models.CharField(blank=True, max_length=255, verbose_name='author')),
                ('abstract', models.CharField(blank=True, max_length=255, verbose_name='abstract')),
                ('journal_reference', models.CharField(blank=True, max_length=255, verbose_name='journal reference')),
                ('category', models.CharField(blank=True, max_length=255, verbose_name='category')),
                ('submitted_date', models.CharField(blank=True, help_text='The expected format is [YYYYMMDDTTTT+TO+YYYYMMDDTTTT] were the TTTT is provided in 24 hour time to the minute, in GMT. We could construct the following query using submittedDate.', max_length=50, verbose_name='submitted date')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_default=django.db.models.functions.datetime.Now(), verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='updated at')),
                ('extras', models.JSONField(blank=True, default=dict, verbose_name='extras')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='arxiv_searches', related_query_name='arxiv_search', to='librarain.source', verbose_name='source')),
            ],
            options={
                'verbose_name': 'ArXiv Search',
                'verbose_name_plural': 'ArXiv Searches',
            },
        ),
    ]
