# Generated by Django 5.1.8 on 2025-06-20 16:36

import django.core.files.storage
import django.core.validators
import librarain.files
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('librarain', '0010_arxivsearch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(blank=True, max_length=255, storage=django.core.files.storage.FileSystemStorage(), upload_to=librarain.files.document_file_path, validators=[django.core.validators.FileExtensionValidator(['doc', 'docx', 'html', 'md', 'odt', 'pdf', 'rst', 'tex', 'txt'])], verbose_name='file'),
        ),
    ]
