# Generated by Django 5.1.8 on 2025-06-24 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('librarain', '0011_alter_document_file_allow_blank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='license',
            field=models.CharField(blank=True, max_length=255, verbose_name='license'),
        ),
    ]
