# Generated by Django 5.1.8 on 2025-06-30 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('librarain', '0012_allow_blank_document_license'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semanticscholarsearch',
            name='query',
            field=models.CharField(help_text='A plain-text search query string. No special query syntax is supported. Hyphenated query terms yield no matches (replace it with space to find matches.)', max_length=255, verbose_name='query'),
        ),
    ]
