# Generated by Django 5.1.8 on 2025-07-02 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('librarain', '0013_make_semanticscholarsearch_query_requied'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semanticscholarsearch',
            name='open_access_pdf',
            field=models.BooleanField(default=True, help_text='Restricts results to only include papers with a public PDF.', verbose_name='open access PDF'),
        ),
    ]
