# Generated by Django 5.0.2 on 2025-01-02 14:39

import companies.files.storage
import django.db.models.deletion
import django_countries.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('website', models.URLField(blank=True, verbose_name='website')),
                ('duns', models.IntegerField(blank=True, null=True, verbose_name='D-U-N-S number')),
                ('nid', models.IntegerField(blank=True, null=True, verbose_name='Company NID')),
                ('cb_uuid', models.UUIDField(blank=True, null=True, verbose_name='crunchbase UUID')),
                ('cb_url', models.URLField(blank=True, null=True, verbose_name='crunchbase URL')),
                ('linkedin_url', models.URLField(blank=True, verbose_name='linkedin URL')),
                ('facebook_url', models.URLField(blank=True, verbose_name='facebook URL')),
                ('twitter_url', models.URLField(blank=True, verbose_name='twitter URL')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email')),
                ('phone_number', models.CharField(blank=True, max_length=64, verbose_name='phone number')),
                ('hq_country', django_countries.fields.CountryField(blank=True, max_length=2, verbose_name='HQ country')),
                ('hq_region_name', models.CharField(blank=True, max_length=255, verbose_name='HQ state')),
                ('hq_city_name', models.CharField(blank=True, max_length=255, verbose_name='HQ city')),
                ('address_line_1', models.CharField(blank=True, max_length=255, verbose_name='address line 1')),
                ('address_line_2', models.CharField(blank=True, max_length=255, verbose_name='address line 2')),
                ('postal_code', models.CharField(blank=True, max_length=255, verbose_name='postal/zip code')),
                ('image', models.ImageField(blank=True, null=True, upload_to=companies.files.storage.company_image_path, verbose_name='image')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='updated at')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_company', related_query_name='created_companies', to=settings.AUTH_USER_MODEL, verbose_name='creator')),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
            },
        ),
    ]
