# Generated by Django 5.0.2 on 2025-01-15 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='hq_region_name',
            new_name='hq_state_name',
        ),
    ]
