# Generated by Django 5.0.2 on 2025-01-15 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_rename_hq_region_name_company_hq_state_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='cb_url',
            field=models.URLField(blank=True, null=True, unique=True, verbose_name='crunchbase URL'),
        ),
        migrations.AlterField(
            model_name='company',
            name='cb_uuid',
            field=models.UUIDField(blank=True, null=True, unique=True, verbose_name='crunchbase UUID'),
        ),
        migrations.AlterField(
            model_name='company',
            name='website',
            field=models.URLField(blank=True, null=True, unique=True, verbose_name='website'),
        ),
    ]
