# Generated by Django 5.0.2 on 2025-01-15 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_add_unique_company_website_cb_url_cb_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='summary',
            field=models.TextField(blank=True, verbose_name='short description'),
        ),
        migrations.AlterField(
            model_name='company',
            name='description',
            field=models.TextField(blank=True, verbose_name='full description'),
        ),
    ]
