# Generated by Django 5.0.2 on 2025-01-15 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_company_summary_alter_company_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='duns',
            field=models.IntegerField(blank=True, null=True, unique=True, verbose_name='D-U-N-S number'),
        ),
        migrations.AlterField(
            model_name='company',
            name='nid',
            field=models.IntegerField(blank=True, null=True, unique=True, verbose_name='Company NID'),
        ),
    ]
