# Generated by Django 5.0.2 on 2025-01-17 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0011_industry'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='operating_status',
            field=models.CharField(blank=True, choices=[('active', 'Active'), ('closed', 'Closed')], max_length=64, verbose_name='operating status'),
        ),
    ]
