# Generated by Django 5.0.2 on 2025-01-17 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0013_company_technology_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='industries',
            field=models.ManyToManyField(blank=True, related_name='companies', related_query_name='company', to='companies.industry', verbose_name='industries'),
        ),
    ]
