# Generated by Django 5.0.2 on 2025-01-17 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0014_company_industries'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='company_type',
            field=models.CharField(blank=True, choices=[('for_profit', 'For Profit'), ('non_profit', 'Non-Profit')], max_length=64, verbose_name='company type'),
        ),
    ]
