# Generated by Django 5.0.2 on 2025-01-17 08:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0015_company_company_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='funding_stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companies', related_query_name='company', to='companies.fundingstage', verbose_name='funding stage'),
        ),
    ]
