# Generated by Django 5.0.2 on 2025-01-17 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0016_company_funding_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='funding_rounds_count',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='number of funding rounds'),
        ),
    ]
