# Generated by Django 5.0.2 on 2025-01-17 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0018_company_add_more_cb_based_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='investment_stages',
            field=models.ManyToManyField(blank=True, help_text='the stages of investments made by this organization', related_name='investors_companies', related_query_name='investor_company', to='companies.fundingstage', verbose_name='investment stages'),
        ),
        migrations.AlterField(
            model_name='company',
            name='investor_types',
            field=models.ManyToManyField(blank=True, help_text='type of investor this organization is (e.g. Angel, Fund of Funds, Venture Capital)', related_name='companies', related_query_name='company', to='companies.investortype', verbose_name='investor type'),
        ),
        migrations.AlterField(
            model_name='company',
            name='last_equity_funding_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_equity_for_companies', related_query_name='last_equity_for_company', to='companies.fundingtype', verbose_name='last equity funding type'),
        ),
        migrations.AlterField(
            model_name='company',
            name='last_funding_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_for_companies', related_query_name='last_for_campany', to='companies.fundingtype', verbose_name='last funding round type'),
        ),
    ]
