# Generated by Django 5.0.2 on 2025-01-23 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0019_alter_company_related_names'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='postal_code',
            new_name='hq_postal_code',
        ),
        migrations.AlterField(
            model_name='company',
            name='hq_postal_code',
            field=models.CharField(blank=True, max_length=255, verbose_name='HQ postal/zip code'),
        ),
    ]
