# Generated by Django 5.0.2 on 2025-01-27 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0021_company_hq_regions_names'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='extras',
            field=models.JSONField(blank=True, default=dict, verbose_name='extras'),
        ),
    ]
