# Generated by Django 5.0.2 on 2025-03-25 17:44

import django.contrib.postgres.fields
import django.db.models.deletion
import django.db.models.functions.datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0022_company_extras'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatentApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('patent_number', models.CharField(blank=True, max_length=255, verbose_name='patent number')),
                ('number', models.CharField(blank=True, max_length=255, verbose_name='application number')),
                ('confirmation_number', models.SmallIntegerField(blank=True, null=True, verbose_name='application confirmation number')),
                ('invention_title', models.CharField(blank=True, help_text='Clear and concise technical description of the invention as provided by the patent applicant.', max_length=255, verbose_name='invention/application title')),
                ('first_inventor_name', models.CharField(blank=True, help_text='Name of the inventor with Rank One. Listed as first inventor in the patent application.', max_length=255, verbose_name='first inventor name')),
                ('first_applicant_name', models.CharField(blank=True, help_text='Name of the Applicant with Rank One. Listed as first applicant in the patent application.', max_length=255, verbose_name='first applicant name')),
                ('status_code', models.CharField(blank=True, max_length=255, verbose_name='status code')),
                ('status_description', models.CharField(blank=True, max_length=255, verbose_name='status description')),
                ('type_code', models.CharField(blank=True, help_text='The specific value that indicates if the received patent application is considered a domestic application at the National Stage or is submitted as a Patent Cooperative Treaty (PCT) application.', max_length=64, verbose_name='application type code')),
                ('type_label', models.CharField(blank=True, max_length=128, verbose_name='application type label')),
                ('type_category', models.CharField(blank=True, max_length=128, verbose_name='application type category')),
                ('filing_date', models.DateField(blank=True, null=True, verbose_name='filing date')),
                ('grant_date', models.DateField(blank=True, null=True, verbose_name='grant date')),
                ('earliest_publication_date', models.DateField(blank=True, null=True, verbose_name='earliest publication date')),
                ('earliest_publication_number', models.CharField(blank=True, max_length=128, verbose_name='earliest publication number')),
                ('pct_publication_date', models.CharField(blank=True, max_length=128, verbose_name='PCT publication date')),
                ('pct_publication_number', models.CharField(blank=True, max_length=128, verbose_name='PCT publication number')),
                ('publication_categories', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=128), blank=True, default=list, size=None, verbose_name='publication categories')),
                ('publication_dates', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=64), blank=True, default=list, size=None, verbose_name='publication dates')),
                ('publication_sequence_numbers', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=64), blank=True, default=list, help_text='Contains a number assigned to the publication of patent applications filed on or after November 29, 2000. It includes the year, followed by a seven digit number, followed by a kind code. Example: 200011234567A1.', size=None, verbose_name='publication sequence numbers')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_default=django.db.models.functions.datetime.Now(), verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='updated at')),
                ('extras', models.JSONField(blank=True, default=dict, verbose_name='extras')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patent_applications', related_query_name='patent_application', to='companies.company', verbose_name='company')),
            ],
            options={
                'verbose_name': 'Patent Application',
                'verbose_name_plural': 'Patent Applications',
            },
        ),
    ]
