# Generated by Django 5.0.2 on 2025-03-25 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0023_patentapplication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patentapplication',
            name='number',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='application number'),
        ),
        migrations.AddConstraint(
            model_name='patentapplication',
            constraint=models.UniqueConstraint(fields=('number', 'company_id'), name='companies_patentapplication_number_company_id'),
        ),
    ]
