# Generated by Django 5.0.2 on 2025-03-25 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0024_add_patentapplication_number_company_constraint'),
    ]

    operations = [
        migrations.AddField(
            model_name='patentapplication',
            name='status_date',
            field=models.DateField(blank=True, null=True, verbose_name='status date'),
        ),
    ]
