# Generated by Django 5.0.2 on 2025-03-25 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0025_patentapplication_status_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='patent_applications_count',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='number of patent applications'),
        ),
    ]
