# Generated by Django 5.0.2 on 2025-03-26 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0026_company_patent_applications_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='patent_applications_count',
        ),
    ]
