# Generated by Django 5.1.8 on 2025-05-06 18:51

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0027_remove_company_patent_applications_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='name')),
                ('potential_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='potential amount (USD)')),
                ('obligated_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='obligated amount (USD)')),
                ('program_name', models.CharField(blank=True, max_length=255, verbose_name='program name')),
                ('phase', models.CharField(blank=True, max_length=255, verbose_name='phase')),
                ('branch', models.CharField(blank=True, max_length=255, verbose_name='branch')),
                ('sbir_id', models.CharField(blank=True, max_length=255, verbose_name='SBIR award ID')),
                ('award_year', models.PositiveIntegerField(blank=True, null=True, verbose_name='award year')),
                ('award_month', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='award month')),
                ('award_date', models.DateField(blank=True, null=True, verbose_name='award date')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('granting_agency', models.CharField(blank=True, max_length=255, verbose_name='granting agency')),
                ('extras', models.JSONField(blank=True, default=dict, verbose_name='extras')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='updated at')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grants', related_query_name='grant', to='companies.company', verbose_name='company')),
            ],
            options={
                'verbose_name': 'Grant',
                'verbose_name_plural': 'Grants',
                'indexes': [models.Index(fields=['award_year', 'award_month'], name='companies_grant_award_ym_idx')],
            },
        ),
    ]
